### ISSUE TITLE
MutableGraph unwanted self link added in cluster

### ISSUE THREAD

**Issue by evrooije** [nidi3/graphviz-java#100]
For some reason I get a d -> d link in the output, even though I did not ask for one ... Not sure if I am doing something wrong or if this is an issue?

```java
Graphviz.useEngine(new GraphvizJdkEngine());

MutableGraph root = mutGraph().setDirected(true);
MutableGraph cluster1 = mutGraph("cluster1").setCluster(true);
MutableGraph cluster2 = mutGraph("cluster2").setCluster(true);

MutableNode na = mutNode("a");
MutableNode nb = mutNode("b");
cluster1.add(na);
cluster1.add(nb);

MutableNode nc = mutNode("c");
MutableNode nd = mutNode("d");
Link l = nc.linkTo(nd);
cluster2.add(nc);
cluster2.add(nd);
cluster2.addLink(l);

cluster1.addTo(root);
cluster2.addTo(root);

Graphviz.fromGraph(root).render(Format.XDOT).toOutputStream(System.out);
Graphviz.fromGraph(root).render(Format.PNG).toFile(new File("test.png"));
```

Output (graph, node and edge styling stripped):

```
digraph {
	node [label="\N"];
	subgraph cluster_cluster1 {
		a;
		b;
	}
	subgraph cluster_cluster2 {
		c;
		d;
		c -> d;
		d -> d;
	}
}
```

So there is a c->d and a d->d... I also tried removing the cluster2 addLink but then c->d does not appear. Tried only adding the link and not the nodes, but then the nodes fall outside the cluster. Tried only adding c and the link, and not adding d, but then d falls outside the cluster. Changed the order in which nodes and links are added to the cluster, none of my permutations seem to work ... Is there anything else I can try?

P.s. I need this declarative way of creating nodes due to the source data I need to traverse using 2 nested for loops and dynamically adding nodes and links based said source data in some arrays holding the information (so can't do the graph.add(graph.add(node.link())) sort of thing, it needs to do everything step wise and declarative).

**Comment by evrooije** [comment]
I got it to work by creating the clusters first and using the use((gr, ctx) ->) adding nodes and edges, then creating the main graph again using use((gr, ctx) ->) adding the clusters to the graph there. I'm pretty sure I can work around the recursiveness by flattening my code a bit by doing multiple passes through my arrays.

I am not sure though if I actually ran into an issue that you may want to look into or not... Is it maybe because doing both a linkTo and addLink duplicates the edge? Is it even allowed to do so?

The code, for anyone else that runs into a similar issue:

```java
Graphviz.useEngine(new GraphvizJdkEngine());

MutableGraph cluster1 = mutGraph("cluster1").setCluster(true).use((gr, ctx) -> {
	mutNode("a");
	mutNode("b");
});
MutableGraph cluster2 = mutGraph("cluster2").setCluster(true).use((gr, ctx) -> {
	MutableNode nc = mutNode("c");
	MutableNode nd = mutNode("d");
	nc.addLink(nd);
});

MutableGraph root = mutGraph().setDirected(true).use((gr, ctx) -> {
	cluster1.addTo(gr);
	cluster2.addTo(gr);
});

Graphviz.fromGraph(root).render(Format.XDOT).toOutputStream(System.out);
Graphviz.fromGraph(root).render(Format.PNG).toFile(new File("test.png"));
```

**Comment by nidi3** [comment]
`cluster2.addLink(l);` adds a link from the cluster (not the c node) to the d node.
So, instead of `Link l = nc.linkTo(nd); cluster2.addLink(l);` use just `nc.addLink(nd)`

I agree, the API is a little bit confusing...

**Comment by evrooije** [comment]
Hi Stefan, it works thanks! That seems to do the trick indeed :)
