### ISSUE TITLE
Nashorn has been deprecated

### ISSUE THREAD

**Issue by offbynull** [nidi3/graphviz-java#103]
Running in Java11 gives back the following warning: ```Warning: Nashorn engine is planned to be removed from a future JDK release```. Would it be easy to migrate the Javascript engine used to graalvm?

**Comment by nidi3** [comment]
I don't know what exactly the migration path from Nashorn to GraalVM is/will be.
What I can do is to make sure that the js code is compatible with Graal's js engine and use Graal's js engine when it's available on the class/module path.
Is that what you meant?

**Comment by offbynull** [comment]
Yes. My understanding is Nashorn is being completely removed from the JVM. But, I think GraalVM's JS engine is exposed through the same JSR-223 script API that Nashorn is.
