### ISSUE TITLE
graph dpi

### ISSUE THREAD

**Issue by mx1up** [nidi3/graphviz-java#104]
hello,

is it possible to set the DPI to render a graph at (default=72 is quite low)? I found the following [answer on stackoverflow](https://stackoverflow.com/questions/1286813/how-do-i-set-the-resolution-when-converting-dot-files-graphviz-to-images) for the DOT language but fail to find a java equivalent.

I mean something like this:
```
        Graphviz.fromGraph(graph)
                .dpi(300)
                .engine(Engine.DOT)
                .render(Format.PNG)
                .toFile(pngFile);
```

is it possible?
thanks!
matthias

**Comment by nidi3** [comment]
You can do `graph().graphAttr().with("dpi", 300)` but I'm not sure that it does the expected thing. I'll have to test it.

**Comment by mx1up** [comment]
thanks for the hint!

Weirdly, when i add this graph attr, the output resolution is higher but i get a blank sheet! I'm using the the mutable api rendering with V8 on windows (fallback from dot). This is my code:
```
        graph = <mutable graph creation code>
        graph.graphAttrs().add("dpi", "300"); // only added this line
        Graphviz.fromGraph(graph)
                .engine(Engine.DOT)
                .render(Format.PNG)
                .toFile(pngFile);
```
I will test on linux tonight (with dot)

**Comment by mx1up** [comment]
unfortunately, I have the same result on linux (where dot is available). I did have a warning from svgsalamander about some color that could not be parsed. i will further investigate (this error probably also comes when omitting the dpi param)

**Comment by nidi3** [comment]
There was a problem with the generated svg file and/or the rendering of it.
It should work now (with 0.8.4) work as expected.

**Comment by nidi3** [comment]
For the color parsing problem, please open another issue.

**Comment by mx1up** [comment]
thanks, it works!
