### ISSUE TITLE
Resizing graph node to fit small text

### ISSUE THREAD

**Issue by rococode** [nidi3/graphviz-java#105]
I feel this is a simple question but I wasn't able to find anything about it in docs/older issues.

How can I get a graph node to roughly fit the text it contains, when the text is small?

Right now I'm getting something like this:

![](https://i.imgur.com/OdTjZSd.png)

This uses `Font.size(2)` on the bottom right node. What I want is for that rectangle to be sized so that it wraps more closely to the text and maybe gets slimmed down, rather than the huge empty space and thick stroke that it uses right now.

As an example, making it look like this would be nice:

![](https://i.imgur.com/yqCUzSq.png)

Here is the code I have for that bottom-right node:

        Node oneA = node("test1-attributes").with(
                Label.lines(Label.Justification.LEFT,
                        String.format("%-" + longestKey + "s: %s", "key", "value"),
                        String.format("%-" + longestKey + "s: %s", "key133", "value18")
                ),
                Font.name("monospace"),
                Font.size(2),
                Shape.RECTANGLE
        );

**Comment by nidi3** [comment]
The size of a node depends on its content. But it has a minimum size and margins around the text.
To set these, use: `Size.std().size(0,0).margin(0,0))`

**Comment by rococode** [comment]
Yes, that worked. Thanks!
