### ISSUE TITLE
Nodes with same label

### ISSUE THREAD

**Issue by leandersonandre** [nidi3/graphviz-java#106]
Is possible to create nodes with same label?

![Screen Shot 2019-04-17 at 17 00 28](https://user-images.githubusercontent.com/16268923/56317077-53945580-6132-11e9-9c85-3669ed9bdcf8.png)

**Comment by nidi3** [comment]
use the Label attribute: `graph().with(node("a").with(Label.of("Q3")),node("b").with(Label.of("Q3")))`

**Comment by leandersonandre** [comment]
Thanks @nidi3, its work well
