### ISSUE TITLE
Unable to generate graph and error is Error:(18, 1) java: package com.eclipsesource.v8 does not exist. can you please help me on this

### ISSUE THREAD

**Issue by tamir123** [nidi3/graphviz-java#111]

**Comment by tamir123** [comment]
Hello niddi,

Hope you are doing well, i am trying to generate graph for my nlp project(Master's) mapping actors -> usecases in the use-case diagram. i heared about your work and i was very much interested. I am getting output like this :

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/stanford-corenlp-full-2018-10-05/slf4j-simple.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/tamir/.m2/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/tamir/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.11.1/log4j-slf4j-impl-2.11.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]

Process finished with exit code 0

Can you please help me on this

**Comment by tamir123** [comment]
I am testing with simple example

 public static void main(String[] args) throws Exception {

        Graphviz.useEngine(new GraphvizJdkEngine());

        Graph g = graph("example1").directed()
                .graphAttr().with(RankDir.LEFT_TO_RIGHT)
                .with(
                        node("a").with(Color.RED).link(node("b")),
                        node("b").link(to(node("c")).with(Style.DASHED))
                );
        Graphviz.fromGraph(g).height(100).render(Format.PNG).toFile(new File("example/ex1.png"));

**Comment by nidi3** [comment]
You seem to have problems with dependencies. Are you using maven? What's your `pom.xml`?
- For the SLF4J issue, the message says that there are 3 implementations of SLF4J on the classpath: `slf4j-simple`, `logback-classic`, `log4j-slf4j-impl`. Remove 2 of them from pom.xml.
- The main issue is probably because `j2v8-` dependencies are missing. This should not happen normally.

**Comment by tamir123** [comment]
Thanks it is working fine @niddi, thank you a lot. will approach you if i find any other problem. its fine whoo
thank you !

On May 12, 2019 at 4:51 AM, Stefan Niederhauser <notifications@github.com> wrote:



You seem to have problems with dependencies. Are you using maven? What's your pom.xml?

For the SLF4J issue, the message says that there are 3 implementations of SLF4J on the classpath: slf4j-simple, logback-classic, log4j-slf4j-impl. Remove 2 of them from pom.xml.
The main issue is probably because j2v8- dependencies are missing. This should not happen normally.
