### ISSUE TITLE
Using TreeMap

### ISSUE THREAD

**Issue by tamir123** [nidi3/graphviz-java#113]
Hello Niddi,

Thanks for all previous support.

I am using a tree map for keys and values. I want to draw graph for keys and its values. 
i have to draw from keys to its values in one graph [Actors and Use-cases diagram]. can you please give me some idea on this. for example actors (Keys) are Bank manager, Customer, Employee  and Use cases(Values) are Monitor opeation, generatesummary...etc.

BANK MANAGER ==> [MONITOROPERATION, MAKE VISIT TOBRANCH, GENERATESUMMARY OF REPORT, VIEWREPORT, GENERATESUMMARY, SUBMIT TOMANAGEMENT]
CUSTOMER ==> [UPDATECUSTOMER DETAIL, CAN VIEWCUSTOMER DETAIL]
EMPLOYEE ==> [LOG INSYSTEM, MUST ENTEREMPLOYEE ID, CAN VIEWEMPLOYEE CALENDER ACTIVITY, SENDNOTIFICATION]

Please let me know if you have any idea on this.

regards
tamir

**Comment by nidi3** [comment]
You mean something like this?
```
Map<String, List<String>> map = new HashMap<>();
map.put("a", asList("b", "c"));
map.put("b", asList("d", "c"));
        
MutableGraph g = mutGraph();
for (Map.Entry<String, List<String>> entry : map.entrySet()) {
    MutableNode node = mutNode(entry.getKey());
    for (String to : entry.getValue()) {
        node.addLink(to);
    }
    g.add(node);
}
```

**Comment by tamir123** [comment]
Hello My friend hope you are doing alright
 you are great dude in this and i appreciate you so much !!! :

Thanks and regards
tamir

**Comment by nidi3** [comment]
Thanks for the nice words!

**Comment by tamir123** [comment]
Hello niddi,

Hope you are doing great and i am thankful for your support through my project and it is in great shape and a good work. All graphics credit goes to your great ideas in graphics.

i just need one a clarification as i am printing the graph like the file attached (Ist attachment). But want to replace the node with a picture instead of oval shapes in actors as depicted in the 2nd attachment.

But it is printing the same as Ist attachement. Please help me out like always.
![tamir1234](https://user-images.githubusercontent.com/25845373/60423299-f40cf880-9bfe-11e9-85ed-5d5f135e8d6f.png)




I am using the following code my friend:

 Graphviz.useEngine(new GraphvizJdkEngine());
       //Graphviz.useEngine(new GraphvizCmdLineEngine());
 MutableGraph g = mutGraph().setDirected(true)     .graphAttrs().add(RankDir.LEFT_TO_RIGHT,Color.WHITE.gradient(Color.rgb("888888")).background()
                         .angle(90)).nodeAttrs().add(Color.GOLD4.radial(90),Color.BLACK.font());

       //Graphviz.useEngine(new GraphvizCmdLineEngine());

        for(Map.Entry<String,List<String>> mapping : actorsUseCase.entrySet())

        {
            System.out.println(mapping.getKey() + " ==> " + mapping.getValue());
            MutableNode node = mutNode(mapping.getKey()).add( Image.of("actor.png"));
           // MutableNode node = mutNode(mapping.getKey()).add(Label.html("<table border='0'><tr><td><img src='actor.png' /></td></tr></table>"));

            for (String usecaselist : mapping.getValue()) {

                //node.addLink(usecaselist);

                node.addLink(usecaselist);



            }
             g.add(node);

           Graphviz gg = Graphviz.fromGraph(g).height(600);

         //  Graphviz.fromGraph(g).basedir(new File("example")).height(600).render(Format.PNG).toFile(new File("example/tamii.png"));

           gg.basedir(new File("example")).render(Format.PNG).toFile(new File("example/tamir1234.png"));

![IMG_20190701_124902](https://user-images.githubusercontent.com/25845373/60423099-79dc7400-9bfe-11e9-9915-31b0b7aecc51.jpg)

#113 Treemap
