### ISSUE TITLE
Cannot create a mixed directed/undirected graph

### ISSUE THREAD

**Issue by marco-brandizi** [nidi3/graphviz-java#114]
I'm trying to build a graph programmatically that has both directed and undirected edges. Following [this suggestion](https://stackoverflow.com/a/13236978/529286), I've tried to create two subgraphs and add them into a top container:

```java
MutableGraph containerGraph = Factory.mutGraph ()
	.setDirected ( true )
	.graphAttrs ().add ( RankDir.LEFT_TO_RIGHT );

// Shoul yield A->B
MutableGraph digraph = Factory.mutGraph ().setDirected ( true ).graphAttrs ().add ( RankDir.LEFT_TO_RIGHT );
digraph.add ( Factory.mutNode ( "A" ).addLink ( Factory.mutNode ( "B" ) ) );

// Should yield A-C
MutableGraph graph = Factory.mutGraph ().setDirected ( false ).graphAttrs ().add ( RankDir.LEFT_TO_RIGHT );
graph.add ( Factory.mutNode ( "A" ).addLink ( Factory.mutNode ( "C" ) ) );

containerGraph.add ( digraph );
containerGraph.add ( graph );

Graphviz viz = Graphviz.fromGraph ( containerGraph );
viz.render ( Format.PLAIN ).toOutputStream ( new FileOutputStream ( "target/dot-merge-test.dot" ) );
viz.render ( Format.PNG ).toOutputStream ( new FileOutputStream ( "target/dot-merge-test.png" ) );
```

I expected the result to have nested subgraph blocks, but the result has everything merged into a single graph, which of edges are all directed (as per the top container):

```txt
graph 1 2 1.25
node A 0.375 0.625 0.75 0.5 A solid ellipse black lightgrey
node B 1.625 1 0.75 0.5 B solid ellipse black lightgrey
node C 1.625 0.25 0.75 0.5 C solid ellipse black lightgrey
edge A B 4 0.72287 0.72747 0.85327 0.76748 1.005 0.81404 1.1458 0.85724 solid black
edge A C 4 0.72287 0.52253 0.85327 0.48252 1.005 0.43596 1.1458 0.39276 solid black
stop
```

**Comment by marco-brandizi** [comment]
OK, I've found a way, though I don't know if/how subgraphs can be created:

```java
MutableGraph graph = Factory
	.mutGraph ()
	.setDirected ( true )
	.graphAttrs ()
	.add ( RankDir.LEFT_TO_RIGHT );

MutableNode a = Factory.mutNode ( "A" );
MutableNode b = Factory.mutNode ( "B" );
MutableNode c = Factory.mutNode ( "C" );

graph.add ( a, b, c );
a.addLink ( Factory.to ( b ).add ( Arrow.NONE ) );
a.addLink ( Factory.to ( c ).add ( Arrow.NORMAL ) );
```

**Comment by nidi3** [comment]
This is not directly supported by the graphviz language.
There is only `subgraph` but not `subdigraph`.
A similar solution to yours is using the `dir` attribute: https://stackoverflow.com/questions/13236975/graphviz-dot-mix-directed-and-undirected
I'll think if it's possible to apply `dir=none` if there's any undirected subgraph inside a directed one.

**Comment by nidi3** [comment]
With Version 0.8.8, your example works.

**Comment by marco-brandizi** [comment]
Thanks. Version 0.8.8 [doesn't seem to be on Maven](https://mvnrepository.com/artifact/guru.nidi/graphviz-java) yet.

**Comment by nidi3** [comment]
It's here right now http://repo1.maven.org/maven2/guru/nidi/graphviz-java/
