### ISSUE TITLE
Using Treemap

### ISSUE THREAD

**Issue by tamir123** [nidi3/graphviz-java#117]
Hello niddi,

Hope you are doing great and i am thankful for your support through my project and it is in great shape and a good work. All graphics credit goes to your great ideas in graphics.

i just need one a clarification as i am printing the graph like the file attached (Ist attachment). But want to replace the node with a picture instead of oval shapes in actors as depicted in the 2nd attachment.

But it is printing the same as Ist attachement. Please help me out like always.

I want to make like this : 
![IMG_20190701_124902](https://user-images.githubusercontent.com/25845373/60505908-baf38780-9cd5-11e9-82ac-d4f568413478.jpg)

**Comment by nidi3** [comment]
Your code should work. Is the `actor.png` in the `example` directory?

**Comment by nidi3** [comment]
Try with a different image and/or add `Shape.NONE, Color.rgba("00000001"), Label.of("")` to the actor nodes.

**Comment by tamir123** [comment]
My friend,

I tried with different images and ways it is not replacing the nodes with the diagram :
MutableNode node = mutNode(mapping.getKey()).add(Size.std().margin(.10,.9),Image.of("diagram_1.png"),Color.rgba("00000001"));
I have doubts below are the few points below 
1: can you please tell if any particular size is required for image as this image size is 166X116 and i am using only png format.
2: I am using only  Graphviz.useEngine(new GraphvizJdkEngine()); not //Graphviz.useEngine(new GraphvizCmdLineEngine()); as you can see in the previous comment.
3: must i change/add any maven dependency ?
4:or must i include something else ? 
5. I am using your repository in my project since May 12,2019

Please let me know your ideas. I really want to put the image.
And Like always stand ups for your help and co-operation.

thanks,

**Comment by nidi3** [comment]
Can you try it now with the new 0.8.10 version?

**Comment by tamir123** [comment]
Yes, it working dude,..... Thank you so much man it is amazing tool you have done really hats off!!!!!!.
thanks a lot for your co-operation and support man.

![image](https://user-images.githubusercontent.com/25845373/60885739-57330680-a261-11e9-99ad-33192158cbb8.png)

Can you just let me know if we can put a border or box over the nodes as shown in previous comment of mine dear

once again thanks and keep going up man you are amazing !

**Comment by nidi3** [comment]
just add `Shape.RECTANGLE, Label.of("...").locate(Label.Location.BOTTOM)` to the actor node's attributes. And add some whitespace to the bottom of the image.

**Comment by tamir123** [comment]
Perfect my friend, thanks !!!! All great the picture 

Can you just let me know if possible to put a box like this below:

https://user-images.githubusercontent.com/25845373/60805406-081da080-a191-11e9-8e89-7631f29bd0d7.png

Thanks for all the things 
You are great ! Hats off dude

**Comment by nidi3** [comment]
A cluster subgraph should do the trick

**Comment by tamir123** [comment]
Mmmmm... Let me try it my friend ... 

thank you so much !:)

**Comment by tamir123** [comment]
Done dude !!!, Everything is cool and nice after applying cluster. nice work an thanks a lot for your reply and answers.

Great! Great! Great! . Thanks niddi it means a lot to me. Always keep flying :))))))
