### ISSUE TITLE
rasterize using dot instead of batik/svgsalamander

### ISSUE THREAD

**Issue by mx1up** [nidi3/graphviz-java#119]
Hi,

I have trouble outputting a graph to png on a raspberry pi. Enabling the antialiasing on the Graphics2D yields some weird rendering artifacts which makes the output unreadable. So this is a problem on its own which can probably be solved by fiddling on the pi, but then I thought: is it not possible to rasterize the graph using dot itself (i.e. -Tpng:cairo) bypassing the rasterization using batik/svgsalamander altogether? That would make it much faster and more memory efficient i guess and it would fix my antialiasing problem at once since I already successfully converted to png with CLI dot command with antialiasing.
Or does that not fit well into the framework?

cheers
matthias

**Comment by nidi3** [comment]
With version `0.9.0` there's `Rasterizer.builtIn()` to rasterize directly with graphviz. However, this works only with `GraphvizCmdLineEngine`.

**Comment by mx1up** [comment]
nidi, you're awesome :) it works!
