### ISSUE TITLE
Make totalMemory of viz.js configurable over the Java API

### ISSUE THREAD

**Issue by sparsick** [nidi3/graphviz-java#12]
If you render a large graph, following exception can be thrown:

```
guru.nidi.graphviz.engine.GraphvizException: Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 
Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which adjusts the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 

	at guru.nidi.graphviz.engine.GraphvizV8Engine.doExecute(GraphvizV8Engine.java:64)
	at guru.nidi.graphviz.engine.AbstractGraphvizEngine.execute(AbstractGraphvizEngine.java:51)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:68)
	at guru.nidi.graphviz.engine.Renderer.toImage(Renderer.java:64)
	at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:52)
```

The reason is that graphviz-java uses the default value (16MB) for the available total memory for the Emscripten module instance (see the [documentation of viz.js](https://github.com/mdaines/viz.js#vizsrc-options-formatsvg-enginedot-scale-images-path-width-height--totalmemory16777216-) ). The exception message signals that more memory is needed. It's possible in viz.js to increase this value for the total memory (BTW, more memory helps in my case ). But unfortunately, I can't set this value over the Java API. 

It would be nice if the total memory value can be configurable over the  `Graphviz` class.

**Comment by nidi3** [comment]
Good point! Merging as soon as the pull request is ready.

**Comment by nidi3** [comment]
Thanks for the PR, it's merged.

**Comment by luxmar** [comment]
I get the error

> Exception in thread "main" guru.nidi.graphviz.engine.GraphvizException: abort("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value 16777216, (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime but prevents some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 "). Build with -s ASSERTIONS=1 for more info.

despite 

setting the total memory size by using toalMemory 

`				Graphviz.fromGraph(g).totalMemory(999999999).render(Format.SVG).toFile(new File("ex1.svg"));
`

**Comment by nidi3** [comment]
This is working for me (with an even number like 1000000000). Are you using the latest version? Which GraphvizEngine?

**Comment by luxmar** [comment]
Thank you very much for your answer. It works now. I was indeed not using the latest version.
I was working with version 0.8.1 instead of version 0.10.1
