### ISSUE TITLE
Retrieving DOT file

### ISSUE THREAD

**Issue by AmanGotchu** [nidi3/graphviz-java#120]
Is it possible to export a dot file after constructing a graph?

**Comment by nidi3** [comment]
I don't think so but it would be easy to implement. What do you want to do with it?

**Comment by AmanGotchu** [comment]
I just want the functionality to use the manipulated dot file at my own convenience. In my specific case, I have a way of handling dot files and visualizing them already and just want the end result dot file.

**Comment by AmanGotchu** [comment]
Would it be OK if I were to work on that feature?

**Comment by nidi3** [comment]
I already did it: a988b7494ffbafbd08435b33cb7a43006bbbe351

**Comment by AmanGotchu** [comment]
Thanks so much! Will this automatically be available in Maven and do I have to change the version number on my dependency?

**Comment by nidi3** [comment]
Version 0.10.0, available in 1-2 hours.

**Comment by AmanGotchu** [comment]
Thanks again!
