### ISSUE TITLE
Generated SVG has not the expected format warning

### ISSUE THREAD

**Issue by Stawicki-CompactBI** [nidi3/graphviz-java#122]
Specifying SVG render format can sometimes cause: `Generated SVG has not the expected format. There might be image size problems.` warning, which causes the SVG translate scale attribute not to be removed. I believe this might have to do with the fact that SVG_PATTERN pattern (`"<svg width=\"(\\d+)p[tx]\" height=\"(\\d+)p[tx]\"(.*?)>\n"
                    + "<g(.*?)transform=\"(scale\\(.*?\\))?"`) specifies new line separator as `\n` char, whereas in my case it was `\r\n`. I think using `\s*` instead should solve the issue. I'm using GraphvizCmdLineEngine with Graphviz 2.38.0.
Temporary fix that worked for me was setting the dpi attribute of graph explicitly to empty value:
`graph.graphAttrs().add("dpi", "");`

**Comment by nidi3** [comment]
Thanks for the catch.
Windows newlines and regexes, two things to avoid 😃
