### ISSUE TITLE
Clusters

### ISSUE THREAD

**Issue by AmanGotchu** [nidi3/graphviz-java#123]
Is it possible to assign a group of nodes with their own set of edges in a cluster without defining "cluster specific" edges?

How are clusters used in this library?

**Comment by nidi3** [comment]
Can you give an example of what you want do achieve?
Can you do this with the native dot implementation or would it be an extension?

**Comment by AmanGotchu** [comment]
https://graphviz.gitlab.io/_pages/Gallery/directed/cluster.html

Yep, its possible with native DOT -> Graphviz implementation. Just not sure if this library has support for it.

**Comment by nidi3** [comment]
Just use `.cluser()`:
```
Graph g = graph().with(
    graph("1").cluster().graphAttr().with(Label.of("#1")).with(node("a0").link("a1")),
    graph("2").cluster().graphAttr().with(Label.of("#2")).with(node("b0").link("b1")),
    node("start").link("a0", "b0"));
```

**Comment by AmanGotchu** [comment]
Is this possible with MutableGraphs?

**Comment by nidi3** [comment]
`.setCluster()`

**Comment by AmanGotchu** [comment]
I'm able to create clusters and add them to my overall graph, but I can't find a way to set the rank of specific clusters inside the overall graph so only some (potentially all) start at the same spot.

**Comment by nidi3** [comment]
How would you do it in DOT?

**Comment by jeremydouglass** [comment]
> a way to set the rank of specific clusters inside the overall graph so only some (potentially all) start at the same spot

Do you mean like swim lanes?

https://www.google.com/search?q=swim+lanes+graphviz

**Comment by AmanGotchu** [comment]
Swim lanes are similar to what I want. I ended up figuring it out though! I had to make all edges that connect different clusters "constraint"="false"

**Comment by nidi3** [comment]
So, closing the issue.
