### ISSUE TITLE
Broken Elipse Rendering

### ISSUE THREAD

**Issue by nsoft** [nidi3/graphviz-java#125]
I recently tried an upgrade from 0.5.2 to 0.10.1 or 0.11.0 and both produce a broken elipse shown here: https://github.com/nsoft/jesterj/issues/136

Plan being visualized (via https://github.com/nsoft/jesterj/wiki/Plan-Providers#visualization)  has about 12 such steps, I'll seek permission to release the full image if you like but this occurs in a run of single elipses, about 3/4 of the way down the image. The code being visualized however is proprietary so I can't give it to you to play with.

**Comment by nsoft** [comment]
code invoking graphviz can be seen here: https://github.com/nsoft/jesterj/blob/master/code/ingest/src/main/java/org/jesterj/ingest/model/impl/PlanImpl.java#L85

**Comment by nidi3** [comment]
This is strange. Have you tried different rasterizers (Salamander, Batik , builtIn)? 
When you generate an SVG?

**Comment by nidi3** [comment]
Any news here?

**Comment by nsoft** [comment]
Sorry haven't had a chance to test other rasterizers. Have to look up how to do that, and visualization is secondary to my current attempts to get my project running on Jdk11. I will get back to it eventually.

**Comment by nsoft** [comment]
I eventually found this to be fixed in 0.16
