### ISSUE TITLE
Extra dir property generated when updating from 0.8.0 to 0.9.0

### ISSUE THREAD

**Issue by vanniktech** [nidi3/graphviz-java#126]
When updating from 0.8.0 to the latest, I've noticed that in 0.9.0 the generation seems to have changed:

```diff
digraph "G" {
node ["fontname"="Times New Roman"]
-"singleempty" ["shape"="egg","color"="#ff0099","style"="dotted","label"="singleempty"]
+"singleempty" ["style"="dotted","label"="singleempty","shape"="egg","color"="#ff0099"]
{
+edge ["dir"="none"]
graph ["rank"="same"]
"singleempty"
}
}
```

How come the order of the attributes have changed? Are they deterministic, meaning the order won't change?

Also, how come there's the new edge with dir none being written to the file?

**Comment by nidi3** [comment]
The order of the attributes is not important, so it's undefined. Or it there a reason for a defined order?
As for the "dir", I'll have a look.

**Comment by vanniktech** [comment]
I do use this particular library to assert against the DOT text file. Hence, I'd like to have a deterministic order otherwise I keep on changing my unit tests.

**Comment by nidi3** [comment]
I'm going to use a `LinkedHashMap` for the attributes, so their order will be preserved.
The "dir" attribute is added when you have nested graphs, some directed and some undirected. This does not work with graph/digraph so, instead dir=none/forward is used instead.

**Comment by nidi3** [comment]
version `0.11.1`
