### ISSUE TITLE
Rendering to PNG doesn't use all of the space

### ISSUE THREAD

**Issue by StFS** [nidi3/graphviz-java#127]
When I render a dot file to a PNG, the output from using graphviz-java is different from using the dot executable on my machine.

Both produce PNG images of the same size (4214x116) but the java rendering has a bunch of space that is not utilized and just transparent.

Attached are the dot file itself and both output files (output_dot.png and output_java.png).

Here is the input dot file (I had to change the ending to .txt to get GitHub to accept it as an attachment):
[dependenyGraph.dot.txt](https://github.com/nidi3/graphviz-java/files/3698102/dependenyGraph.dot.txt)

The code I'm using to produce the java output png is as simple as it gets:
`Graphviz.fromFile(file).render(Format.PNG).toFile(new File("output_java.png"));`

Here's the output PNG of that:
![output_java](https://user-images.githubusercontent.com/1756/66324358-c974bf00-e914-11e9-8614-6300416015b2.png)

And the dot command I use to produce the dot output is:
`dot -Tpng dependenyGraph.dot -o output_dot.png`

And this is the output PNG of that:
![output_dot](https://user-images.githubusercontent.com/1756/66324357-c974bf00-e914-11e9-828b-6c60a7d0db48.png)

I would have expected that the two outputs should be the same. Is there something else I should be configuring in my Java code to get the output the same as when I use the dot command?

**Comment by mx1up** [comment]
you can the java code make use the dot command for creating raster output, much more efficient and should be same result ;) to do that, use the builtIn rasterizer (see docs for full example):

`viz.width(200).rasterize(Rasterizer.builtIn("png")).toFile(new File("example/ex5p"));`

**Comment by StFS** [comment]
Well, no, the main reason that I'm using this library is to avoid having to have the dot binary installed. So I specifically want to use the java implementation, otherwise I'd just call the executable myself.

**Comment by nidi3** [comment]
Indeed, dpi settings seem to help. Instead of `Graphviz.fromFile(new File(...))` you can do `Graphviz.fromGraph(Parser.read(new File(...))`.
The latter automatically sets 96 DPI and thus fixes the size.

**Comment by StFS** [comment]
@nidi3 Thanks for the reply. Unfortunately, I tried that and there is no difference.

**Comment by StFS** [comment]
I also tried setting the DPI to 96 explicitly and there is no difference:

`Graphviz.fromGraph(Parser.read(file).graphAttrs().add("dpi", 96)).render(Format.PNG).toFile(new File("output_fixdpi.png"));`

The size of the output file changes but there is always the "empty space" around the actual image... so the whole size of the image is not being utilized.

**Comment by StFS** [comment]
I have a feeling that there may be a misunderstanding as to what I'm talking about.

The problem is not that the output image is "too small"... the output image is 4214x116 pixels just as the one produced by the `dot` executable. The problem is that the content in that image does not fill out all the canvas. It's "squeezed" into the top left corner. The rest of the image is just transparent.

Here is an image where I've colored the transparent area of the image blue.

![output_fromfile_with_blue_bg](https://user-images.githubusercontent.com/1756/68591794-6c2adb00-0489-11ea-81c3-78f5c542e61c.png)

Changing the DPI only resizes the whole image, the transparent / unused area is still present.

**Comment by nidi3** [comment]
Interestingly, my native dot version gives an images width of 5619px.
However, I improved the handling in version `0.11.1`. 
`Graphviz.fromFile(file).render(Format.PNG).toFile(new File("output_java.png"));` should do the right thing now.

**Comment by mx1up** [comment]
welcome back @nidi3 , seems like you had a nice vacation ;)

**Comment by StFS** [comment]
Yup. That's it, thanks!

Fixed in https://github.com/nidi3/graphviz-java/releases/tag/graphviz-java-parent-0.11.1

**Comment by StFS** [comment]
@nidi3 5619px means that you're using 96 dpi default. I seem to be using 72 dpi default.

According to the documentation, 96 should be the default... I have no idea why mine seems to be something else.

> Then it is converted to device units, according to -Gdpi, or a dpi value that is given by the output device, or a default that is provided by each render. There are separate dpi values for x and y to allow for non-square pixels. Some renderers invert the Y axis and need an offset to place the origin in the top left corner. The default dpi for -Tpng is 96dpi (approximating the resolution of most computer monitors) so this is where the scaling by 96/72 (4/3) comes from.

https://graphviz.gitlab.io/faq/#FaqCoordTransformation

Maybe it has something to do with _"or a dpi value that is given by the output device"_? Just wondering whether that overrides the default value?

**Comment by nidi3** [comment]
Yes, it's 96 dpi for png and 72 dpi for svg _on my machine_. 
So if it's important, you have to manually specify the dpi value.

**Comment by nidi3** [comment]
> welcome back @nidi3 , seems like you had a nice vacation ;)

@mx1up Yes, thanks, 1 month of summer prolongation ;)
