### ISSUE TITLE
Graphviz.scale() overwrites height and width values when it's used in a method chain

### ISSUE THREAD

**Issue by sparsick** [nidi3/graphviz-java#13]
I use the static methods (`scale()`, `heigth()`, `width()`) in a method chaining for configuring Graphviz. Unfortunately, the `scale()` method overwrites the height and width values to 0.

Following failing unit test demonstrates the behaviour

```java
 @Test
    public void methodChainCheck(){
        final Graph graph = graph().with(node("a").link("b"));

        final Graphviz graphviz = Graphviz.fromGraph(graph).height(20).width(30).scale(3);

        assertThat(graphviz.width, is(30) );
        assertThat(graphviz.height, is(20) );
        assertThat(graphviz.scale, is(3d ));
    }
```

Test result is:
```
java.lang.AssertionError: 
Expected: is <30>
     but: was <0>
Expected :is <30>
     
Actual   :<0>
``` 

My expectation would be that this test runs successfully.

This same behaviour is watchable if `width()`or `height()` is the last method call in a method chain.

**Comment by nidi3** [comment]
merged.
