### ISSUE TITLE
how to use image map 

### ISSUE THREAD

**Issue by liumin6688** [nidi3/graphviz-java#134]
does graphviz-java support image map  function?

or Can I get the coordinates of each node?

**Comment by nidi3** [comment]
The general question is: What do you want to achieve? An image map or a list of node coordinates or something else?

The "imap" and "cmapx" formats are currently not supported, but could easily be done.
The coordinates could probably be determined from the json format, I guess.

**Comment by liumin6688** [comment]
thanks a lot for your answer 
what I want to achieve ： for example there is some nodes and some links in my picture, when mouse over on some nodes, I'd like to show some other information, And I use Java to draw the picture, so I need to know the coordinates of each node and link

**Comment by nidi3** [comment]
You can use any attribute e.g. `node.with("URL", "http://...")` .
I'm going to have a look at this.

**Comment by liumin6688** [comment]
thank you very much, To sum up : I need coordinates of all the nodes and edges

**Comment by nidi3** [comment]
Or even more high level: Given a coordinate, you need to calculate the corresponding node/edge, right?

**Comment by liumin6688** [comment]
No.I don't need this, I just want the coordinate of each node/edge after the picture is finished, not draw a picture by the given coordinate of each node/edge

**Comment by nidi3** [comment]
So what's the coordiante of a polygon/ellipse/spline?

**Comment by liumin6688** [comment]
this is a demo from ”cmapx“
```
<area shape="poly" id="node1" href="googlr.com" title="node1" alt="" coords="1112,429,1105,422,1086,415,1056,410,1018,407,976,405,934,407,896,410,866,415,847,422,840,429,847,437,866,443,896,449,934,452,976,453,1018,452,1056,449,1086,443,1105,437"/>
<area shape="poly" id="node2" href="google.com" title="node2" alt="" coords="790,573,785,566,770,559,746,554,717,551,684,549,651,551,622,554,598,559,583,566,578,573,583,581,598,587,622,593,651,596,684,597,717,596,746,593,770,587,785,581"/>
<area shape="poly" id="edge46" href="google.com" title="if" alt="" coords="933,455,740,548,738,542,930,449"/>
<area shape="rect" id="edge46-label" href="google.com" title="if" alt="" coords="872,477,883,497"/>
<area shape="poly" id="node3" href="google.com" title="node3" alt="" coords="1079,573,1074,566,1059,559,1035,554,1006,551,973,549,941,551,911,554,888,559,873,566,868,573,873,581,888,587,911,593,941,596,973,597,1006,596,1035,593,1059,587,1074,581"/>
<area shape="poly" id="edge45" href="google.com" title="if" alt="" coords="979,453,977,535,971,535,972,453"/>
```

- shape="poly"  -> it represent polygon/ellipse/spline
- coords="933,455,740,548,738,542,930,449"  -> it represent coordinates of one node/edge

I need these two information or other format which can be convert to these
Thank you so much

**Comment by liumin6688** [comment]
I find that: SVG format maybe meet my needs,if It is ,I will tell you,Thanks

**Comment by liumin6688** [comment]
```java
Graphviz graphviz = Graphviz.fromGraph(graph);
graphviz.render(Format.PNG).toFile(new File(imagePath + name + ".png"));
graphviz.render(Format.DOT).toFile(new File(imagePath + name + ".dot"));
```
I use this code to generate picture and dot file, and then convert the dot file to cmapx file,
But I find that :  the coordinates from cmapx  file  doesn't map the node/edge in png picture, because  when call render() method ,a new Graphviz will be created,so graphviz.render(Format.PNG) and graphviz.render(Format.DOT) aren't the same graph ,Is it right?

**Comment by liumin6688** [comment]
@nidi3 ,thanks  SVG format  meets my needs. you can ignore my issue now, Thank you so much. https://github.com/nidi3/graphviz-java/issues/134#issuecomment-561502579 this is another solution.

**Comment by nidi3** [comment]
Nice that you found a solution. 

I'm currently implementing a solution based on the json format and I also see some mismatch between png and shapes coordinates which I'm trying to correct. I hope I can release this today.

Yes, `.render` returns a new `Graphviz` but based on the same `Graph` so there should not be a problem. 
How do you convert dot into cmapx? Calling the native graphviz executable?
You can try `.rasterizer(Rasterizer.builtIn("png"))` maybe this produces a slightly different png which matches the cmapx coordinates better.

After finishing my solution, I can have a look at the new problem. Can you share your dot file?

Btw. you can just write `new File(imagePath + name)` the correct suffix will be added automatically ;)

Let me

**Comment by liumin6688** [comment]
Thanks, yes I call the native graphviz executable to generate cmapx. So this is the reason why  there is some mismatch between png and shapes coordinates ? 

when use this to generate Json file
```java
Graphviz.fromGraph(graph).render(Format.JSON).toFile(new File( name));
```
this error happened
```
13:06 ERROR [c.n.a.a.e.AclExceptionHandler] Format: "json" not recognized. Use one of: bmp canon cmap cmapx cmapx_np dot emf emfplus eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg metafile pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4

guru.nidi.graphviz.engine.GraphvizException: Format: "json" not recognized. Use one of: bmp canon cmap cmapx cmapx_np dot emf emfplus eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg metafile pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.4

	at guru.nidi.graphviz.engine.GraphvizCmdLineEngine.execute(GraphvizCmdLineEngine.java:76)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:224)
	at guru.nidi.graphviz.engine.Renderer.execute(Renderer.java:133)
	at guru.nidi.graphviz.engine.Renderer.toFile(Renderer.java:54)

```

there are some secret info in my dot file,I will give you a part of it. is It enough?

![1575523012](https://user-images.githubusercontent.com/47554511/70206194-aa9e7780-1761-11ea-84d1-44569ad95ccd.png)

But when use `.rasterizer(Rasterizer.builtIn("cmapx"))` ,It is better than Calling the native graphviz executable,But there are still some mismatch.

**Comment by nidi3** [comment]
Maybe you have installed an old version of graphviz which does not support json format? I have version 2.40.1 and it works.

As for the mismatch: Can you produce both `png` and `cmapx` with native dot? Is there still a mismatch?
I found that there can be mismatches between `svg` and `json` and that's what I'm trying to fix inside graphviz-java.

**Comment by liumin6688** [comment]
@nidi3 ,sorry to ask you another question again
```java
	Graph g = graph("example1").directed().linkAttr().with().nodeAttr().with()
			.graphAttr().with(Rank.dir(TOP_TO_BOTTOM)).with(
			node("a").with(Color.RED).with(Shape.TRIANGLE).link(node("b1")),
			node("a").with(Color.RED).link(node("b2")),
			node("b1").with(Shape.RECTANGLE).link(to(node("c1")).with(Style.FILLED, Label.of("if"))),
			node("b1").link(to(node("c2")).with(Style.DASHED)),
			node("b1").link(to(node("c3")).with(Style.DASHED)),
			node("b2").with(Shape.RECTANGLE).link(to(node("c1")).with(Style.DASHED)),
			node("b2").link(to(node("c2")).with(Style.DASHED)),
			node("b2").link(to(node("c3")).with(Style.DASHED)),
			node("c1").link(to(node("d")).with(Style.DASHED)),
			node("c2").link(to(node("d")).with(Style.DASHED)),
			node("c3").link(to(node("d")).with(Style.DASHED))
		);
```

the picture from the demo is like this
![sort](https://user-images.githubusercontent.com/47554511/70780757-3b0f3480-1dc0-11ea-966c-e756c416a047.png)

Is there some api used for sorting,I'd like to sort (b2,b1)- >(b1,b2), (c3,c1,c2) ->(c1,c2,c3),thank you so much
