### ISSUE TITLE
How to create different node with the same text?

### ISSUE THREAD

**Issue by LeeReindeer** [nidi3/graphviz-java#135]
Is there any method to create some different node refs with the same text?

For example:

```java
    Graph graph = graph().directed()
        .with(node("a").link(node("a")));
```

Result:
![test1](https://user-images.githubusercontent.com/22074258/70328196-6bf8e200-1873-11ea-8038-811ea26893f9.png)

What I want:

![test2](https://user-images.githubusercontent.com/22074258/70328225-77e4a400-1873-11ea-9ba5-4d5a2a6b5877.png)

**Comment by nidi3** [comment]
Use the `Label` attribute: `node("1").with(Label.of("a")).link(node("2").with(Label.of("a")))`

**Comment by LeeReindeer** [comment]
Cool thanks
