### ISSUE TITLE
Cannot create link between nodes in parent graph

### ISSUE THREAD

**Issue by thombergs** [nidi3/graphviz-java#136]
Hi,

I want to do something like [this](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%20%20%20%20edge%20%5B%22dir%22%3D%22forward%22%5D%0A%20%20%20%20graph%20%5B%22rankdir%22%3D%22LR%22%5D%0A%20%20%20%20%0A%20%20%20%20subgraph%20%22cluster_internal%20components%22%20%7B%0A%20%20%20%20%20%20%20%20edge%20%5B%22dir%22%3D%22none%22%5D%0A%20%20%20%20%20%20%20%20graph%20%5B%22label%22%3D%22my%20app%22%5D%0A%20%20%20%20%20%20%20%20%22B%22%20%5B%22shape%22%3D%22rectangle%22%5D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20subgraph%20%22cluster_external%20input%20components%22%20%7B%0A%20%20%20%20%20%20%20%20edge%20%5B%22dir%22%3D%22none%22%5D%0A%20%20%20%20%20%20%20%20graph%20%5B%22label%22%3D%22input%22%2C%22style%22%3D%22dashed%22%5D%0A%20%20%20%20%20%20%20%20%22A%22%20%5B%22shape%22%3D%22rectangle%22%5D%0A%20%20%20%20%20%20%20%20%22B%22%20%5B%22shape%22%3D%22rectangle%22%5D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20%22A%22%20-%3E%20%22B%22%0A%7D) (click for preview):

```
digraph {
    edge ["dir"="forward"]
    graph ["rankdir"="LR"]
    
    subgraph "cluster_internal components" {
        edge ["dir"="none"]
        graph ["label"="my app"]
        "B" ["shape"="rectangle"]
    }
    
    subgraph "cluster_external input components" {
        edge ["dir"="none"]
        graph ["label"="input","style"="dashed"]
        "A" ["shape"="rectangle"]
        "B" ["shape"="rectangle"]
    }
    
    "A" -> "B"
}
```

But I can't figure out how to add the link (A->B) to the parent graph. When I call `node.addLink()` the link always appears within one of the subgraphs, resulting in [this](https://dreampuf.github.io/GraphvizOnline/#digraph%20%7B%0A%20%20%20%20edge%20%5B%22dir%22%3D%22forward%22%5D%0A%20%20%20%20graph%20%5B%22rankdir%22%3D%22LR%22%5D%0A%20%20%20%20%0A%20%20%20%20subgraph%20%22cluster_internal%20components%22%20%7B%0A%20%20%20%20%20%20%20%20edge%20%5B%22dir%22%3D%22none%22%5D%0A%20%20%20%20%20%20%20%20graph%20%5B%22label%22%3D%22my%20app%22%5D%0A%20%20%20%20%20%20%20%20%22B%22%20%5B%22shape%22%3D%22rectangle%22%5D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20subgraph%20%22cluster_external%20input%20components%22%20%7B%0A%20%20%20%20%20%20%20%20edge%20%5B%22dir%22%3D%22none%22%5D%0A%20%20%20%20%20%20%20%20graph%20%5B%22label%22%3D%22input%22%2C%22style%22%3D%22dashed%22%5D%0A%20%20%20%20%20%20%20%20%22A%22%20%5B%22shape%22%3D%22rectangle%22%2C%22label%22%3D%22A%20to%20B%22%5D%0A%20%20%20%20%20%20%20%20%22B%22%20%5B%22shape%22%3D%22rectangle%22%5D%0A%20%20%20%20%20%20%20%20%22A%22%20-%3E%20%22B%22%0A%20%20%20%20%7D%0A%7D):

```
digraph {
    edge ["dir"="forward"]
    graph ["rankdir"="LR"]
    
    subgraph "cluster_internal components" {
        edge ["dir"="none"]
        graph ["label"="my app"]
        "B" ["shape"="rectangle"]
    }
    
    subgraph "cluster_external input components" {
        edge ["dir"="none"]
        graph ["label"="input","style"="dashed"]
        "A" ["shape"="rectangle","label"="A to B"]
        "B" ["shape"="rectangle"]
        "A" -> "B"
    }
}
```

The link is within the second `subgraph`, causing the arrow not to show the arrowhead.

I tried adding the link directly to the parent graph using `graph.addLink()`, but this will always assume that the graph itself is the source of the link, which is not what I want.

Is there a way to add a link to the main graph to get the result in the first code snippet above?

**Comment by thombergs** [comment]
I have found a solution to add a link to the main graph by doing this:

```java
mainGraph.add(node("A")
                        .link("B"))
```

However, this way, I cannot add attributes (like a label) to the link, ass `link()` returns a `Node` and not a `Link`. 

How can I add a link between two nodes to the main graph and manipulate the attributes of the link?

**Comment by nidi3** [comment]
Hi, sorry for the late answer. You can do
`mainGraph.add(node("A").link(to(node("B")).with(Style.DOTTED)`
