### ISSUE TITLE
Set Node Position

### ISSUE THREAD

**Issue by TwilightSparks** [nidi3/graphviz-java#138]
I know that only DFP/NEATO support the position information. I wonder is there a function to set the position for a mutNode?

Any help would be greatly appreciated!

**Comment by nidi3** [comment]
I don't know which attribute you mean for position, but you can set any attributes like this:
`mutNode("test").add("attribute", "value")`

**Comment by TwilightSparks** [comment]
Thank you for replying my problem, what I really want is to put a node in specific position on figure. like this command in dot:
`a [pos="0,0"]`

**Comment by nidi3** [comment]
`mutNode("a").add("pos", "0,0")`

**Comment by TwilightSparks** [comment]
Thank you so much!
