### ISSUE TITLE
j2v8 deps

### ISSUE THREAD

**Issue by mx1up** [nidi3/graphviz-java#139]
hello,

when I make a build of my project, there are different (quite large) jars included vor j2v8 for each platform:
```
j2v8_linux_x86_64-4.6.0.jar
j2v8_macosx_x86_64-4.6.0.jar
j2v8_win32_x86-4.6.0.jar
j2v8_win32_x86_64-4.6.0.jar
```
is it possible to specify a platform and only have that platform be included in the output? Or even: as far as I am aware, I am not using the j2v8 engine, so maybe have it as optional dep?

thanks
matthias

**Comment by nidi3** [comment]
You can just exclude all j2v8 dependencies in your pom:
```
            <exclusions>
                <exclusion>
                    <groupId>com.eclipsesource.j2v8</groupId>
                    <artifactId>*</artifactId>
                </exclusion>
            </exclusions>

```

**Comment by nidi3** [comment]
In version 0.13.0 there'a the `graphivz-java-no-j2v8` module with the j2v8 dependencies marked as optional.

**Comment by mx1up** [comment]
hi Stefan, thanks for sharing your maven-fu as well as making it even easier in 0.13! :medal_military: 
will try it out shortly
