### ISSUE TITLE
Adding labels to edges using Mutable API

### ISSUE THREAD

**Issue by lucaspcamargo** [nidi3/graphviz-java#141]
Hello. I am trying to get my head around the API but can't figure out how to add an edge between two nodes, with a label for the edge. I would appreciate a nudge in the right direction. I must be missing something.

Edit: what I am doing currently (in Scala):
```
      val node = guru.nidi.graphviz.model.Factory.mutNode(src.toString)
      val dstNode = node.addLink(dst.toString)
      val link = node.linkTo(dstNode)
      mg.add( node )
```

**Comment by nidi3** [comment]
You mean `graph().with(node("A").link(to(node("B")).with(Label.of("Edge"))))` ?

**Comment by lucaspcamargo** [comment]
That would be for Immutable graphs, no?

**Comment by nidi3** [comment]
The problem with your code is you're creating a link with `val link = node.linkTo(dstNode)` but it's not added to the node. Adding `node.addLink(link)` should help.
But `mutGraph().add(mutNode("A").addLink(to(mutNode("B")).with(Label.of("Edge"))));` is still nicer in my opinion.

**Comment by lucaspcamargo** [comment]
Oh, I see. The factory APIs makes sense to me now. And your solution is much more elegant. Thank you so much!
