### ISSUE TITLE
Too many dependencies

### ISSUE THREAD

**Issue by juriad** [nidi3/graphviz-java#143]
The library has way too many compile dependencies:
* It certainly does not need `junit-platform-launcher` as a compile dependency (it comes from the parent project).
* I am not entirely sure, but I think that dependency on `jcl-over-slf4j` and `jul-to-slf4j` should not be present either. It should be provided by whoever wants to use such logging framework.
* The graph-viz java itself does not use `comons-io`, it should not be present as a dependency (it comes transitively from `xmlgraphics-commons`.
* `xmlgraphics-commons` is nowhere used, or I couldn't find such place.

Some dependencies can be made optional:
* `commons-exec` needed only when calling `dot` directly by `GraphvizCmdLineEngine` which I personally cannot use in my environment.
* `nashorn-promise` is only used by `JdkJavascriptEngine` (not sure if needed by Graal though).
* `viz.js` is required by any `AbstractJsGraphvizEngine` not by `GraphvizCmdLineEngine`.
* `svgSalamander` should be treated the same way as Batik - it is an optional dependency.

Some dependencies are stated already to be optional, however they are marked as `provided. This should be fixed; see https://medium.com/@danismaz.furkan/difference-between-optional-true-optional-and-scope-provided-scope-7404ec24fb59

**Comment by jeremydouglass** [comment]
@juriad -- do you have a fork / patch demonstrating your refactor that successfully removed dependencies in this way?

**Comment by nidi3** [comment]
Thanks for the deep analysis. I'll definitely have a look at it. 
As a general rule I want the default dependencies to be such that beginners can just use it without any additional configurations needed.

**Comment by nidi3** [comment]
- `junit-platform-launcher` and `xmlgraphics-commons` are removed.
- `commons-io` is changed to test scope
- I keep the slf4j dependencies as some dependencies use jdk-logging and commons-logging. These are abstracted by slf4j. Clients of this lib can then use the slf4j implementations they please as described in the readme.

I agree on the possible optional dependencies, but as said above, I want this library to work directly without some dependency tweaking. Advanced users like you can still exclude unwanted libraries.
If there are better ways to satisfy beginner and advanced users, please tell me.

**Comment by nidi3** [comment]
Added the `graphviz-java-min-deps` module with the optional dependencies you mentioned.
