### ISSUE TITLE
Classloader issues with Nashorn

### ISSUE THREAD

**Issue by juriad** [nidi3/graphviz-java#144]
I am using `graphviz-java` in a plugin (`pf4j`) which means that the library is loaded by a different classloader. This causes issues for `NashornJavascriptEngine` (the only engine I want to use) which is then unable to find `net.arnx.nashorn.lib.PromiseException` (ClassNotFoundException). This class is known to the plugin's classloader but not to the applications's classloader.

I managed to fix it by this:
```
    static {
        // ugly as hell but creates NashornScriptEngine with the correct classloader
        try {
            Class<?> engine = Class.forName("guru.nidi.graphviz.engine.NashornJavascriptEngine");
            Field field = engine.getDeclaredField("ENGINE");
            field.setAccessible(true);

            Field modifiersField = Field.class.getDeclaredField("modifiers");
            modifiersField.setAccessible(true);
            modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL);

            field.set(null, new NashornScriptEngineFactory().getScriptEngine(engine.getClassLoader()));
        } catch (Exception e) {
            throw new RuntimeException("Failed to init the JS engine", e);
        }

        Graphviz.useEngine(new GraphvizJdkEngine());
    }
```

Maybe there should be possibility to set the classloader, or we could set a more sensible default. It is likely that the `PromiseException` exists in the same classloader as `NashornJavascriptEngine`.

**Comment by nidi3** [comment]
Wow, using reflection on reflection classes, cool ;)
I never had problems with classloading here, so I don't really know what to do.
If it helps, I can provide a version where the classloader can be set.
What would be a sensible default? I thought that `Thread.currentThread().getContextClassLoader()` should be mostly ok.
Would other engines have the same issue? I did not see options to change their classloaders, though.

**Comment by nidi3** [comment]
Btw. how could I reproduce the issue?

**Comment by nidi3** [comment]
Default classloader is now `getClass().getClassLoader()`.
If this is not ok, there is `GraphvizLoader.useClassLoader()` to customize the class loader.
