### ISSUE TITLE
Default GraphvizServerEngine is useless

### ISSUE THREAD

**Issue by Clashsoft** [nidi3/graphviz-java#150]
The default engines always contains a `GraphvizServerEngine` instance:

https://github.com/nidi3/graphviz-java/blob/efa069f764046117f92c84fedac82bcd00f23d35/graphviz-java/src/main/java/guru/nidi/graphviz/engine/Graphviz.java#L80

However, as `GraphvizServerEngine#useEngine` is not called by default, it's internal `engines` list is empty. Because of this, it always errors with a timeout exception. This only happens if neither V8 nor Dot is available. The Jdk engine is never reached unless explicitly specified with `Graphviz.useEngine(new GraphvizJdkEngine())`.

**Comment by nidi3** [comment]
There's no timeout when there's already a `GraphvizServer` running. This is the idea behind the Server Engine: keep a process running to avoid initialization cost.
But it's probably a special case which is better not in the default engines list.
