### ISSUE TITLE
Adding margins around a label

### ISSUE THREAD

**Issue by vinaysshenoy** [nidi3/graphviz-java#152]
I'm using this library to generate state machines for representing UI flows in a app, It's been working well so far, but one thing I haven't figured out is how to add spacing between a link and its label.

<img width="846" alt="Screenshot 2020-04-12 at 10 17 26 PM" src="https://user-images.githubusercontent.com/1978065/79074797-febaf900-7d0b-11ea-8aaf-65d11af48de9.png">

If you look at the labels here, they are really close to the link. Is there any way I can add some spacing there?

**Comment by nidi3** [comment]
Edge lables are a weak point of graphviz. The only workaround I see is manually adding spaces to your labels.

**Comment by vinaysshenoy** [comment]
Ah, I see. Thanks for letting me know!
