### ISSUE TITLE
Warning: Nashorn engine is planned to be removed from a future JDK release

### ISSUE THREAD

**Issue by manikmagar** [nidi3/graphviz-java#153]
FYI - Using Nashorn engine on JDK11+ results in this warning:
Warning: Nashorn engine is planned to be removed from a future JDK release

See [JEP-372](https://openjdk.java.net/jeps/372).

**Comment by manikmagar** [comment]
Looking at https://github.com/nidi3/graphviz-java/blob/master/graphviz-java/src/main/java/guru/nidi/graphviz/engine/JdkJavascriptEngine.java, it attempts to first load GraalVM engine if available, otherwise Nashorn engine. Should the document/readme be updated for this warning?

**Comment by jeremydouglass** [comment]
Looks like the readme says:

> Use this javascript version of graphviz and execute it on the V8 javascript engine. This is done with the bundled J2V8 library.
> Alternatively, the javascript can be executed on Java's own Nashorn or GraalVM engine.

...which implies the fallback order is Viz.js-on-J2V8, then Nashorn, then GraalVM. So maybe that could be updated?

To me it seems like isolating nashorn with a version check should be fine.

**Comment by manikmagar** [comment]
[Viz.js-on-J2V8](https://github.com/nidi3/graphviz-java/blob/master/graphviz-java/src/main/java/guru/nidi/graphviz/engine/GraphvizV8Engine.java) engine and JavaScript engine are two  separate engines, there is no provided fallback order. Client app can choose which one to use and add required dependencies (none for JDK based).

With [GraphvizJdkEngine](https://github.com/nidi3/graphviz-java/blob/master/graphviz-java/src/main/java/guru/nidi/graphviz/engine/GraphvizJdkEngine.java), the order is - Attempt GraalVM first. If it is not available, then fallback to Nashorn engine. Since Nashorn will be removed with JDK15 which will be released in Sept2020, there is still time. But yes, maybe [NashornJavascriptEngine.java](https://github.com/nidi3/graphviz-java/blob/master/graphviz-java/src/main/java/guru/nidi/graphviz/engine/NashornJavascriptEngine.java) should check if JDK version is between 8 and 14 (including) to be able to use Nashorn if needed.

**Comment by jeremydouglass** [comment]
> Since Nashorn will be removed with JDK15 which will be released in Sept2020, there is still time.

Yes, absolutely.

I also want to underscore that Using JDK11 (or 14) in 2025 or 2030 is totally feasible -- just as is using JDK8 today. That doesn't mean that version checking shouldn't be handled gracefully, it just means that Nashorn definitely doesn't fall of a cliff in September for projects that still want to use it just because of JDK15.

**Comment by manikmagar** [comment]
Sounds good 👍
