### ISSUE TITLE
Cannot find Graphviz installed by conda on Windows

### ISSUE THREAD

**Issue by fabiencelier** [nidi3/graphviz-java#154]
I am trying your lib with graphviz installed via conda: `conda install graphviz`

It works on Linux and MacOs but not Windows because GraphvizCmdLineEngine cannot find the dot executable.
On my tests graphviz work in cmd with just `dot` because conda put a `dot.bat` file somewhere in the path that redirect to ./graphviz/dot.exe

I think it is ignored by CommandRunner.which

**Comment by nidi3** [comment]
Should be fixed in the next version (hopefully available today)

**Comment by fabiencelier** [comment]
Ok I will try that once it's avaialble and give you some feedback.
Thanks for the quick reponse

**Comment by fabiencelier** [comment]
Also, if I know where is the dot executable, is there a way to provide this path to the GraphvizCmdLineEngine  ?

**Comment by nidi3** [comment]
That's a good point, I think I'll add that possibility.

**Comment by nidi3** [comment]
version `0.16.0` is here.

**Comment by fabiencelier** [comment]
It now works with graphviz installed via conda on windows, thank you !
