### ISSUE TITLE
Using <FONT FACE="Courier"> generates Error

### ISSUE THREAD

**Issue by maxweissboeck** [nidi3/graphviz-java#157]
This is the .dot file I try to render, with FONT FACE as described here
https://www.graphviz.org/doc/info/shapes.html#html

strict digraph "Grafik für asxsa" {
	layout=dot;
	overlap=false;
	splines=true;
	pack=false;
	center=true;
	forcelabels=true;

	graph [bgcolor=white, fontname=Arial, fontcolor=blue, fontsize=10];
	node[fontname=Arial, fontcolor=black, fontsize=10, height=0.1, width=0.1, margin=0.1];
	edge [fontname=Arial, fontcolor=red, fontsize=10];

	node[shape=plaintext,style=filled,fillcolor="#FFFFA5",margin=0.1];
	Ablaufinformation [
		label=<
		<table border='0' cellborder='1' cellspacing='0' >
			<tr>
				<td align='left'>Tabs 0.2 beta rc05</td>
				<td>2020.04.27 09:08:02</td>
				<td align='right'>K-A</td>
			</tr>
			<tr>
				<td align='left'>Ablauf</td>
				<td align='center' colspan='2'>asxsa</td>
			</tr>
			<tr>
				<td colspan='3'>
				<FONT FACE="Courier">
				Ablauf wurde  generiert mit dem Tabs Wizard <br align='left'/>
				AA - <br align='left'/>ii -<br align='left'/>
				</FONT>
				</td>
			</tr>
		</table>
	>];
}

And this is the Error I'm getting:

guru.nidi.graphviz.engine.GraphvizException: Error: in label of node Ablaufinformation

	at guru.nidi.graphviz.engine.ResultHandler.waitFor(ResultHandler.java:42)
	at guru.nidi.graphviz.engine.GraphvizV8Engine$Env.execute(GraphvizV8Engine.java:99)
	at guru.nidi.graphviz.engine.GraphvizV8Engine.jsExecute(GraphvizV8Engine.java:68)
	at guru.nidi.graphviz.engine.AbstractJsGraphvizEngine.execute(AbstractJsGraphvizEngine.java:38)
	at guru.nidi.graphviz.engine.Graphviz.execute(Graphviz.java:211)
	at guru.nidi.graphviz.engine.Renderer.execute(Renderer.java:133)
	at guru.nidi.graphviz.engine.Renderer.toString(Renderer.java:47)

We are still on version 0.10.2 as an update to a later version broke the layout of the nodes, text did not fit in nodes.

Thanks for the great work!

**Comment by nidi3** [comment]
This works for me. 
How are you processing the file? 
What is the complete stack trace?
And can you give an example that works with `0.11.2` but breaks the layout with current version?

thanks

**Comment by nidi3** [comment]
And can you attach the dot file? Maybe there's a special character in it.

**Comment by maxweissboeck** [comment]
Sorry, after doing a clean build the problem seems gone, will do some more testing and will report the outcome.

**Comment by maxweissboeck** [comment]
It works as expected, sorry for this!

**Comment by nidi3** [comment]
Great!
I'd still like to know what hinders you from updating.

**Comment by maxweissboeck** [comment]
It is Issue #182 that hinders update, will try it out soon, thanks!
