### ISSUE TITLE
Use graphviz engine installed on host

### ISSUE THREAD

**Issue by kerkhofsd** [nidi3/graphviz-java#16]
[Not really an issue]

Since the J2V8 engine gives errors when two different JVM's use J2V8 (https://github.com/eclipsesource/J2V8/issues/39), I think it would be nice to provide an engine that uses the graphviz installed on the host to transform the dot files.

More precisely:
Provide an engine (extends AbstractGraphvizEngine) that can
-) Check if the dot command is available on the host OS
-) On execution uses this dot command with the correct parameters to transform the dot files into an output.

I made a first implementation for this engine in my fork of the project.

Would you be interested to integrate this engine into the graphviz-java project?

Kind Regards,
Daan

**Comment by nidi3** [comment]
Hi @kerkhofsd 
This makes sense to me. I would definitely be interested in integrating it.

thanks & cheers
n

**Comment by nidi3** [comment]
fixed with PR #19
