### ISSUE TITLE
If basedir contains \x then the Javascript engine will try to interpret it as a hex digit and fails

### ISSUE THREAD

**Issue by mennodenhollander** [nidi3/graphviz-java#171]
I cannot execute graphviz-java (0.16.3) in a (sub) directory that starts with 'x'.

Steps to reproduce:
- On windows I run Graphviz in a folder containing \x, e.g. C:\xml-data\
- Then graphviz will execute the render() javascript function.
- Then graphviz (NashornJavascriptEngine) fails and throws an exception pointing to the \x string:
```
guru.nidi.graphviz.engine.GraphvizException: Problem executing javascript
...
Caused by: javax.script.ScriptException: <eval>:1:4555 Invalid hex digit
render(... ,{format:'svg',engine:'dot',basedir:'C:\xml-data\.',images:[]});
```

Maybe the basedir path is not properly escaped?

**Comment by nidi3** [comment]
fixed in `0.17.0`
