### ISSUE TITLE
class attribute for SVG

### ISSUE THREAD

**Issue by winnall** [nidi3/graphviz-java#173]
Is there any way of generating a class attribute on SVG elements? I'm using Graphviz-Java to generate SVG for use in a website and want to control the style with CSS, so class attributes are pretty important to me.

Steve

**Comment by nidi3** [comment]
Currently, this is not supported, but let me think about it

**Comment by winnall** [comment]
Thanks for the rapid response. Where are the class attributes on <g> elements currently generated? I could live with being able to add arbitrary classes to that.

**Comment by nidi3** [comment]
I just found this: https://stackoverflow.com/questions/47146706/how-do-i-associate-svg-elements-generated-by-graphviz-to-elements-in-the-dot-sou#answer-61912397
This solves your issue, right?

**Comment by winnall** [comment]
Thanks. That does what I am looking for. But I don't have a dot file, I generate the diagrams in Java. Does that mean I have to modify `AttributeConfigs`? Or define my own class that implements `Attributes`?

**Comment by winnall** [comment]
OK, I've worked it out. I implemented a class as follows:

`public class CSSAttributes implements Attributes<For> {

    @Override
    public Attributes<? super For> applyTo( MapAttributes<? super For> attrs ) {
        throw new UnsupportedOperationException( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
    }

    static Attributes<? extends ForNode> className( String name ) {
        MapAttributes<ForNode> result = new MapAttributes<>();
        result.add( "class", name );
        return result;
    }

}
`

and called

`node( "node" ).with(CSSAttributes.className("value")`,

which does what I want.

**Comment by nidi3** [comment]
In a more ad hoc way, you could also use `with("class", "...")` or `width(Attributes.attr("class","..."))`

**Comment by nidi3** [comment]
I think I'm going to make `SingleAttributes` public, so this will be possible:
````
class Css extends SingleAttributes<String, ForAll> {
    private Css(String key, String value) {
        super(key, value);
    }

    static Css className(String name) {
        return new Css("class", name);
    }
}
````
