### ISSUE TITLE
"\G" not supported by attribute fields

### ISSUE THREAD

**Issue by pauls4GE** [nidi3/graphviz-java#176]
If there is "\G" in any attribute value in the .dot file, the .svg created replaces the "\G" with the name of the graph.
E.g. -- For the graph below
digraph CASE{
    a [label ="\a\b\G\a\B\C\h"]
    a -> c;
    a -> b;
    b -> c [constraint=false];
  }

The corresponding .svg shows:
![image](https://user-images.githubusercontent.com/66636651/89650373-5586a880-d890-11ea-9db5-1133aa90ec13.png)

**Comment by nidi3** [comment]
That's feature of graphviz. http://www.graphviz.org/doc/info/attrs.html (search for \G)
Why would you use invalid escape sequences like \a, \b anyways?

**Comment by pauls4GE** [comment]
So my use case was populating the graph with some user defined URLs. Some windows users prefer to specify paths using '\'.  I came across this issue and thought it was a bug.

**Comment by nidi3** [comment]
But then you would need to replace "\" with "\\" to show a backslash and \G wouldn't be a problem, right?

**Comment by pauls4GE** [comment]
Yes. I figured out my way around this. I was just expecting the dot parser to handle content within " "  automatically by recognizing that whatever is inside is not an escape sequence.
