### ISSUE TITLE
Line Break problems with update from 0.10.2 to 0.17.0

### ISSUE THREAD

**Issue by maxweissboeck** [nidi3/graphviz-java#182]
We use graphviz-java in an Eclipse + Xtext environment on Windows to visualise flows to business people.  
Problem we have with version 0.17.0 is as following:
Longer texts will be (by our Xtext Generator) automatically cut in shorter text strings, using **\n**
In Eclipse Windows, with native settings (we need this, because we also connect to other systems), this results in **\n\r**  as the final input to graphviz-java. 

This was no problem in version 0.10.2, a text like:

"**This long line\n\r is to long.**"

was displayed inside the graph as

"**This long line
is to long.**"

Now with version 0.17.0 the result in the graph is:

"**This long line
<empy line>
is to long.**"

So there is an extra empty line now, that should not be there in a Windows environment.
Is there any setting to avoid this? Or any param to respect the operating systems defaults?

Thanks, Max

**Comment by nidi3** [comment]
all the quoting and escaping is not too easy 😓

**Comment by nidi3** [comment]
btw I hope you mean \r\n not \n\r

**Comment by maxweissboeck** [comment]
Sorry, it is \r\n 
you are right
