### ISSUE TITLE
Problem when visualize AST with graphviz-java

### ISSUE THREAD

**Issue by longuyen97** [nidi3/graphviz-java#183]
I want to visualize an AST for the following expression: `1 + 2 + 3 == 6`

I would expect something like this to happen: 

<a href="https://imgbb.com/"><img src="https://i.ibb.co/r4rgCc3/output.png" alt="output" border="0"></a>

Notice that I have to pad the label of each node with `ID - *`. If I do not add the padding, the tree would look like following

<a href="https://imgbb.com/"><img src="https://i.ibb.co/xhSnD4y/output.png" alt="output" border="0"></a>

Notices the operator `+` appears twice but will be treated as only one node and so references itself. 

How can I bypass this problem?

**Comment by maxweissboeck** [comment]
Each Node needs to have its own node id, but you can give different nodes the same display name / label.
Example N1 and N2 are different nodes, but each of them can have the label “+“ for display.
See the Graphviz documentation, it‘s all there.

**Comment by longuyen97** [comment]
> Each Node needs to have its own node id, but you can give different nodes the same display name / label.
> Example N1 and N2 are different nodes, but each of them can have the label “+“ for display.
> See the Graphviz documentation, it‘s all there.

I am aware of your point. The implementation of the library however assigns each node's id with its label.

**Comment by longuyen97** [comment]
I found a hack around this problem by assigning each node's label with random unique ID and regex the SVG output of the library with original label.

**Comment by maxweissboeck** [comment]
Could you provide an example? Cause I use it a lot and I never ever had this problem.

**Comment by nidi3** [comment]
I'm not sure, but do you miss the `label` attribute?
`node("id 3").with(Label.of("+"))`
