### ISSUE TITLE
https://beerpay.io/nidi3/graphviz-java Broken Donation

### ISSUE THREAD

**Issue by YunaBraska** [nidi3/graphviz-java#189]
Hi, 
I switched from PlantUml to your nice library as the quality of PlantUml is pretty low. Of curse I am missing some features now and wanted to support you and wish a feature but unfortunately your page https://beerpay.io/nidi3/graphviz-java doesn't work when you want to pay/ It says invalid token.
_BTW my project: https://github.com/YunaBraska/surveys_

greetings Yuna

**Comment by nidi3** [comment]
Hi @YunaBraska 

Thanks for the information, and sorry for the late answer.
I switched now to github sponsors.

As for feature wishes, just ask and I'll see what I can do.

cheers
nidi
