### ISSUE TITLE
beerpay.io stopped there service

### ISSUE THREAD

**Issue by hoall** [nidi3/graphviz-java#190]
Hi @nidi3,

just wanted to sponsor your a beer or two for this awesome library. You saved me from a lot of work.

Unfortantly, beerpay.io stopped there service in favor for github sponsors where I cannot find you. Here is the info: https://beerpay.io/

Maybe you want to use this instead?

Best,
Felix

**Comment by nidi3** [comment]
HI @hoall 

Thanks for the information, I have now setup github sponsors.

And thanks in advance for any beers 🍻

**Comment by nidi3** [comment]
Thanks for the beer!
