### ISSUE TITLE
How to disable log output from version 0.18

### ISSUE THREAD

**Issue by maxweissboeck** [nidi3/graphviz-java#205]
Maybe a stupid question, but we upgraded from version 0.17 to 0.18.2 and now get tons of log messages like this

14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_39' -> 'fixedsize' has its default value 'false'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_40' -> 'fontcolor' has its default value 'black'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_40' -> 'height' has its default value '0.5'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_40' -> 'penwidth' has its default value '1.0'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_42' -> 'fontcolor' has its default value 'black'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_42' -> 'penwidth' has its default value '1.0'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_42' -> 'fixedsize' has its default value 'false'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_43' -> 'fontcolor' has its default value 'black'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_43' -> 'penwidth' has its default value '1.0'.
14:33:04.318 [Worker-8: Building] INFO guru.nidi.graphviz.model.Serializer - INFO  node 'NODE_43' -> 'fixedsize' has its default value 'false'.

How can I turn of this messages?

Thanks, Max

**Comment by maxweissboeck** [comment]
No hint from nobody?

**Comment by arnaud-m** [comment]
You can try the  [no-operation (NOP) logger implementation](https://mvnrepository.com/artifact/org.slf4j/slf4j-nop). 

Hope it helps.

**Comment by maxweissboeck** [comment]
As always, if you know how it is simple :-)


import org.slf4j.LoggerFactory;
import ch.qos.logback.classic.Logger
import ch.qos.logback.classic.Level

Logger root = ( Logger) LoggerFactory.getLogger(org.slf4j.Logger.ROOT_LOGGER_NAME)
root.setLevel(Level.ERROR);
