### ISSUE TITLE
SetEngine

### ISSUE THREAD

**Issue by pushphilipp** [nidi3/graphviz-java#217]
Hi,
I want to use this package for creating a graph on a server where the graphiz package  should not be installed. 
In the Readme i saw that in this case I need to run Graphviz.useEngine() and select a different Engine e.g Nashorn or GraalVM. But i'm not quite sure how to create those maybe someone could help me there?

**Comment by g0rba4ev** [comment]
Hi, does your question still actual?

**Comment by pushphilipp** [comment]
No not anymore :D
