### ISSUE TITLE
doInit() of GraphvizCmdLineEngine will always throw error on Windows

### ISSUE THREAD

**Issue by kerkhofsd** [nidi3/graphviz-java#22]
https://github.com/nidi3/graphviz-java/blob/master/src/main/java/guru/nidi/graphviz/engine/GraphvizCmdLineEngine.java#L61

In the doInit() of the GraphvizCmdLineEngine, is searched for the `dot` executable. 
This should be `dot.exe` for Windows. Otherwise this will always fail on Windows machines.

**Comment by nidi3** [comment]
Fixed via #23
