### ISSUE TITLE
Grapvhiz native in Windows: JSON format not supported.

### ISSUE THREAD

**Issue by kerkhofsd** [nidi3/graphviz-java#24]
When using the GraphvizCmdLineEngine on Windows with a JSON as output, the following error appears:
`Format: "json" not recognized. Use one of: bmp canon cmap cmapx cmapx_np dot emf emfplus eps fig gd gd2 gif gv imap imap_np ismap jpe jpeg jpg metafile pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vml vmlz vrml wbmp xdot xdot1.2 xdot1.`

=> It seems that the JSON output format is not supported on Windows machines.

**Comment by nidi3** [comment]
Maybe updating dot could help.
But otherwise, what should happen other than an exception to be thrown?
Or does this break a test?

**Comment by kerkhofsd** [comment]
Indeed, there are tests that do not run on Windows.
Since now the native dot engine is used first, all the tests that use `Format.JSON` fail on Windows...

I have Graphviz 2.38 installed, which is the latest stable version if I'm correct :-/

**Comment by nidi3** [comment]
For MacOS, there is 2.40.1 available 😁 
I'm going to change the tests so that they use JS instead.
