### ISSUE TITLE
Upgrade to batik 1.9

### ISSUE THREAD

**Issue by joerg-rade** [nidi3/graphviz-java#25]
Hi,

if possible update to batik 1.9 since 1.8 brings in some vulnerabilties.
`mvn org.owasp:dependency-check-maven:aggregate -Dowasp`

![screenshot 756 dependency-check report - mozilla firefox](https://user-images.githubusercontent.com/4637858/27033646-990317f8-4f7a-11e7-8cac-62b5827e9af6.png)

Best regards
Jörg

**Comment by nidi3** [comment]
Hey, that's an interesting plugin!

**Comment by joerg-rade** [comment]
Yep. Discovered it today. @work I'll suggest to put it in the CI pipeline.
grtnx -j

**Comment by nidi3** [comment]
Just thought about putting it into my parent pom 👍
