### ISSUE TITLE
StackOverflowError 

### ISSUE THREAD

**Issue by ddalibor** [nidi3/graphviz-java#27]
when i try to send two parallel requests, or two requests close to each other (time interval between two requests is about 3sec) to the lib to create a 'svg' file  i got StackOverflowError. 
[exception.txt](https://github.com/nidi3/graphviz-java/files/1098098/exception.txt)

**Comment by nidi3** [comment]
hi @ddalibor 
Neither nashorn nor V8 using J2V8 support multithreading out of the box.
I'll have a look at it when I find some time. But right now, multithreading unfortunately is not possible.

**Comment by nidi3** [comment]
I think this has to do with #41
