### ISSUE TITLE
Parser for GraphViz in Java

### ISSUE THREAD

**Issue by Salaboy** [nidi3/graphviz-java#3]
Hi there, this looks like a very interesting project, but you ever find or created a parser for graphviz files? I kinda like your APIs, but it will be great if you can obtain a Graph object from an actual graphviz dot file.

**Comment by nidi3** [comment]
Hi Salaboy
I did not think about dot file parsers till now, but it could be interesting.
 
Do you have a concrete use case in mind or do you just ask generally?

**Comment by Salaboy** [comment]
I have a concrete use case for it.. basically grabing a graph authored here:  http://www.webgraphviz.com and and to manipulate it with Java. Then with your APIs export the result. 
Going two ways is usually needed to build a complete authoring tool for graphs, so that will be a concrete use case for a good parser.

**Comment by nidi3** [comment]
Could be interesting... I'll think about it.

**Comment by Salaboy** [comment]
It seems that they have the Antlr grammar available.. so that means that it is only getting the grammar and generating the graph using your model only.. it shoudn't be too complicated.. but it can take some time to build.

**Comment by nidi3** [comment]
Writing a parser should not be too difficult. But what kind of manipulations do you think of?
The current API is only designed to create models, not to manipulate them.

**Comment by nidi3** [comment]
Never say it's quick and easy... 
But now there's a first version of a parser and a mutable data model.

**Comment by Salaboy** [comment]
@nidi3 thanks.. I will take a look at it.. and come back with some comments.

**Comment by Salaboy** [comment]
Hi @nidi3 the parser is working quite well, but I think that it will be great if we can improve the model a little bit more. Maybe I'm missing something. 

For example: link.to() returns the whole path of where that links takes you to.. instead of just the next node. Is there any simple way to get link.to() limited to the node where the link goes? not the whole path? 

Let me know if you want me to open another issue. 
Cheers

**Comment by nidi3** [comment]
Hi @Salaboy 
Thanks for the feedback. Writing the parser was way easier than creating a nice model...

`link.to()` returns a `LinkTarget` which can be a `NodePoint` which contains a `Node`. Maybe you are confused by `Node.toString()` which shows the node and all its successors?

`allNodes()` returns all nodes of a graph, `nodes()` only the root/initial/leftmost nodes. Maybe renaming `allNodes`->`nodes` and `nodes`->`rootNodes` would help?

I hope, I could clarify things.
Don't hesitate to open new issues if there's more questions/ideas.
