### ISSUE TITLE
Change the height of a graph

### ISSUE THREAD

**Issue by abhijitdhar** [nidi3/graphviz-java#30]
My output SVG graph is more stretched out horizontally.
How do I make it stretch vertically a bit more?

**Comment by tomasbjerre** [comment]
Same for me. Here I have specified 500x500.
![dependencies](https://user-images.githubusercontent.com/439571/35198392-895899b2-feee-11e7-8780-ba9a88242ab4.png)

**Comment by nidi3** [comment]
What happens when you just specify a width of e.g. 1000?

**Comment by tomasbjerre** [comment]
Removing `height` has no effect. Seems like changing the text in the nodes does have effect. Adding newlines makes the graph a bit more readable.

**Comment by nidi3** [comment]
Could you attach the dot file so that i can try it out?

**Comment by tomasbjerre** [comment]
These were created with width 1024 and no height.

[Uploading dependencies.zip…]()

**Comment by tomasbjerre** [comment]
If it helps, here is my project: https://github.com/tomasbjerre/maven-repository-dependency-visualizer

**Comment by nidi3** [comment]
This is what I get from your dot file, looks ok to me...
`Graphviz.fromFile(new File("dependencies.dot")).width(1024).render(PNG).toFile(new File("out.png"));`

![out](https://user-images.githubusercontent.com/668297/35485687-72d03310-0463-11e8-9b9e-dc9e281d12c2.png)

**Comment by tomasbjerre** [comment]
Yes, works for me now as well.

Might have been me relocating the lib that caused the problem...

**Comment by nidi3** [comment]
ok, whatever... closing the issue.
