### ISSUE TITLE
API leads to confusion between node ids and labels

### ISSUE THREAD

**Issue by alexeyr** [nidi3/graphviz-java#31]
Given that Node constructor takes Label, and Label supports HTML, I expected

    Factory.graph().with(Factory.node(Label.html("<b>a</b>")))

to work and produce bold "a". However, in my tests it produces a node with text "<b>a</b>" as label, when rendered on JSVGCanvas. Instead, I need 

    Factory.mutGraph().with(Factory.node("some random id").with("label", Label.html("<b>a</b>"))))

Is this the expected result, or is it just failure on Batik's side?

**Comment by nidi3** [comment]
You are right, there's a confusion. I'm going to look at this.

**Comment by nidi3** [comment]
Finally, this works now as expected.
