### ISSUE TITLE
MutableGraph.rootNodes() may return incorrect result on parsed graph

### ISSUE THREAD

**Issue by VladRassokhin** [nidi3/graphviz-java#32]
Here's snippet:
```java
MutableGraph graph = Parser.read(new File("src/test/resources/test1.dot"));
Assert.assertEquals(5, graph.rootNodes().getSize());
```
Reason is after Parser added some nodes into LinkedHashSet (MutableGraph#nodes field) it alternates them later so `MutableNode#hashCode` returns another result and `Graph#add(node)` adds same node twice into set.

Workaround is to call `MutableGraph#copy()` after parsing it `MutableGraph graph = Parser.read(new File("src/test/resources/test1.dot")).copy();`.

Solution could be to change `MutableNode#hashCode` and `MutableNode#equals` to use only `MutableNode#label`.

**Comment by nidi3** [comment]
Finally fixed in version `0.12.1`
