### ISSUE TITLE
It is a wrapper library?

### ISSUE THREAD

**Issue by mcheung63** [nidi3/graphviz-java#33]
It is a wrapper library? Do i need to install graphviz into my machine first? thanks

**Comment by NKame** [comment]
Yes it's a wrapper, but no you don't need to install GraphViz: the wrapper tries to use the local GraphViz first, then the JavaScript on V8 version, then a GraphViz server, and eventually the JavaScript on Nashorn version.

**Comment by mcheung63** [comment]
thanks a lot

**Comment by nidi3** [comment]
Thanks @NKame for answering!
