### ISSUE TITLE
Can't parse graph with directed subgraph

### ISSUE THREAD

**Issue by Boreeas** [nidi3/graphviz-java#37]
A directed graph does not propagate its directed property to subgraphs, so the following fails to parse
```graphviz
digraph g {
	subgraph g1 {
		A -> B
	}
}
```

**Comment by kris7t** [comment]
I am facing the same issue. As a workaround, you can make your graph non-directed by some string manipulation like

    str.replace("digraph", "graph").replace("->", "--")

if you don't actually need a directed graph but still want to accept directed graph input. I am using this hack to extract layout information from xdot files, [like this](https://github.com/kris7t/petridse/blob/c297bde3394c589d0646e00731b1c2a744f5e382/plugins/hu.bme.mit.inf.ecore2pn.exporter.petridotnet/src/hu/bme/mit/inf/ecore2pn/exporter/petridotnet/layout/graphviz/GraphvizLayoutEngine.xtend#L37). It may be possible to set the `MutableGraph` and its subgraphs to directed afterwards, but I didn't check.
