### ISSUE TITLE
Crash when Graphviz not installed and falling back on JS port

### ISSUE THREAD

**Issue by tomasbjerre** [nidi3/graphviz-java#43]
Happens on Ubuntu 17 and Windows 7.

I'm relocating the lib inside a fat jar.... perhaps that is why. But it would still be very nice if I could do that. To create a self contained runnable jar.

I'm getting this now:
```
[main] INFO se.bjurr.mrdv.mavenrepositorydependencyvisualizer.guru.nidi.graphviz.engine.AbstractGraphvizEngine - Could not initialize se.bjurr.mrdv.mavenrepositorydependencyvisualizer.guru.nidi.graphviz.engine.GraphvizCmdLineEngine
se.bjurr.mrdv.mavenrepositorydependencyvisualizer.guru.nidi.graphviz.engine.GraphvizException: dot command not found
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000005e5de2b2, pid=5004, tid=0x00000000000020f8
#
...
```

**Comment by nidi3** [comment]
Nope, if graphviz is not installed, it tries to use the js port of it.
But a JVM crash should never ever happen 😠

**Comment by tomasbjerre** [comment]
I avoided relocation of the lib, still packaging it in a fat jar, and that worked! Now it falls back on JS.
