### ISSUE TITLE
Not an issue, just praise

### ISSUE THREAD

**Issue by stefan-reich** [nidi3/graphviz-java#44]
Hi, I integrated GraphViz-java into my Java dialect, [JavaX](http://javax.tinybrain.de), which makes applications using it easy to build & very easy to distribute. [Here's an example.](http://tinybrain.de/1013688)OS

It should work out-of-the-box on Win (32 bit JVM) and Linux/64 with no GraphViz installed, just a JVM plus [my file](http://tinybrain.de/x30.jar).

I haven't added the other platforms' native libs yet (Mac OS, Win/64) as my system currently downloads all of listed jars regardless of the actual OS and that seemed a bit excessive.

Keep up the good work, this is amazing!

**Comment by nidi3** [comment]
Hi Stefan 
Thanks for the flowers! It's always nice when people use the stuff one builds.

I had a quick look at JavaX. Looks interesting, but I did not found any syntax/language description, am I missing something?
