### ISSUE TITLE
Support for -y option of dot program

### ISSUE THREAD

**Issue by mbassara** [nidi3/graphviz-java#47]
Please, add to _graphviz-java_  possibility to achieve the same behavior as for such command:
`dot -Tdot -y -o output.dot input.dot`

Lets say I have such `input.dot` file:
```dot
graph {
    { rank=same; top}
    { rank=same; right; left; center}
    { rank=same; bottom}

    top -- right -- bottom
    top -- left -- bottom
    left -- center -- right
}
```

Now, the output of command: `dot -Tdot -y -o output.dot input.dot` gives me following result:
```dot
graph {
	graph [bb="0,180,209.3,0"];
	node [label="\N"];
	{
		graph [rank=same];
		top		 [height=0.5,
			pos="104,18",
			width=0.75];
	}
	{
		graph [rank=same];
		right		 [height=0.5,
			pos="182,90",
			width=0.75827];
		left		 [height=0.5,
			pos="27,90",
			width=0.75];
		center		 [height=0.5,
			pos="104,90",
			width=0.9027];
	}
	{
		graph [rank=same];
		bottom		 [height=0.5,
			pos="104,162",
			width=1.011];
	}
	top -- right	 [pos="119.41,32.83 133,45.022 152.7,62.704 166.35,74.959"];
	top -- left	 [pos="88.418,33.166 74.971,45.39 55.659,62.946 42.296,75.094"];
	right -- bottom	 [pos="166.22,105.17 153.04,116.99 134.3,133.8 120.84,145.89"];
	left -- center	 [pos="54.07,90 59.791,90 65.513,90 71.234,90"];
	left -- bottom	 [pos="42.582,105.17 55.59,116.99 74.085,133.8 87.375,145.89"];
	center -- right	 [pos="136.6,90 142.63,90 148.66,90 154.69,90"];
}
```

But using _graphviz-java_ with following code:
```java
MutableGraph mutableGraph = Parser.read(new File("input.dot"));

Graphviz.useEngine(new GraphvizV8Engine());
Graphviz.fromGraph(mutableGraph).engine(Engine.DOT).render(Format.XDOT).toFile(new File("output.dot"));
```
gives result different than the native _dot_ program:
```dot
graph {
	graph [bb="0,0,218.28,180"
	];
	node [label="\N"];
	{
		graph [rank=same];
		top		 [height=0.5,
			pos="108,162",
			width=0.75];
	}
	{
		graph [rank=same];
		right		 [height=0.5,
			pos="189,90",
			width=0.81321];
		left		 [height=0.5,
			pos="27,90",
			width=0.75];
		center		 [height=0.5,
			pos="107,90",
			width=0.96177];
	}
	{
		graph [rank=same];
		bottom		 [height=0.5,
			pos="108,18",
			width=1.0667];
	}
	top -- right	 [pos="124.39,147.43 138.26,135.1 158.06,117.5 172.08,105.04"];
	top -- left	 [pos="91.608,147.43 77.555,134.94 57.413,117.03 43.367,104.55"];
	right -- bottom	 [pos="172.22,75.082 158.78,63.136 139.96,46.41 126.17,34.151"];
	left -- center	 [pos="54.188,90 60.239,90 66.29,90 72.342,90"];
	left -- bottom	 [pos="43.392,75.43 56.89,63.431 76.006,46.439 89.942,34.052"];
	center -- right	 [pos="141.91,90 147.8,90 153.69,90 159.57,90"];
}
```

You can see the difference in the second lines of the output files:
```dot
dot -y                               graphviz_java
graph [bb="0,180,209.3,0"];    vs    graph [bb="0,0,218.28,180"
```

It would be great if you could give me some advice how to achieve the same result like with '_dot -y_' command or please add support for such option.

**Comment by nidi3** [comment]
The problem with this is that the Javascript version of dot (viz.js) does not support -y
What is your output format? xdot? or SVG or PNG?
You could render SVG and then use SVG to rotate the result.

**Comment by jeremydouglass** [comment]
Could submit as a feature request to https://github.com/mdaines/viz.js perhaps...

**Comment by mbassara** [comment]
I need _xdot_ output format because I do not need the image itself but only the layout information. Then I parse output dot and extract coordinates of vertices and edges. I use _graphviz_ only to layout my graphs, I draw them using my own solution.

@jeremydouglass is right, we should start with [viz.js](https://github.com/mdaines/viz.js) feature request

**Comment by nidi3** [comment]
Issue openend on viz.js.
When you are processing the xdot yourself, couldn't you invert the coordinates yourself?

Just thinking about writing a rasterizer that generates images from xdot...

**Comment by mbassara** [comment]
I could but it's not top-priority issue for me so I can wait till _-y_ will be added to viz.js
