### ISSUE TITLE
How to color a label?

### ISSUE THREAD

**Issue by JLLeitschuh** [nidi3/graphviz-java#48]
I want to make my link and my link label have the same color.
It seems like if I want to do this, I'll need to specify the label as `html` and format it myself. Any tips? I'm entering uncharted territory.

**Comment by JLLeitschuh** [comment]
Nvm:
```kotllin
.link(to(vizNodeEnd).with(Label.of("$frequency"), color, color.font()))
```
Using `color.labelFont()` doesn't work.

**Comment by nidi3** [comment]
Hm. I tried this 
`Graph g=graph().with(node("a").link(to(node("b")).with(Label.of("red"),Color.RED,Color.RED.font())));` 
and it renders a red link and a red label...
This does not work for you?

**Comment by JLLeitschuh** [comment]
This did work for me. Thanks!
```
.link(to(vizNodeEnd).with(Label.of("$frequency"), color, color.font()))
```
