### ISSUE TITLE
multiple lines between two nodes

### ISSUE THREAD

**Issue by argsno** [nidi3/graphviz-java#49]
It seem that Viz support multiple lines between two nodes, but fail in this package.

Example:
```java
Graph g = graph("example1").directed().with(node("a").link(node("b"))).with(node("a").link(node("b")));
Graphviz.fromGraph(g).width(200).render(Format.PNG).toFile(new File("example/ex1.png"));
```

**Comment by nidi3** [comment]
Did you mean 
`Graph g2 = raph("example1").directed().with(node("a").link(node("b")),node("b").link(node("a")));
` ?

**Comment by nidi3** [comment]
Simply use 
`graph().directed().with(node("a").link(node("b")).link(node("b")));`
or even 
`graph().directed().with(node("a").link("b").link("b"));`

**Comment by argsno** [comment]
Can I add it respectively?

**Comment by nidi3** [comment]
`graph().directed().with(node("b").link(node("a").link(node("b"))));` ?

**Comment by argsno** [comment]
Thanks, but I mean add two line with two statements?

**Comment by argsno** [comment]
Beacuse I add line dynamically.

**Comment by nidi3** [comment]
```
Node a = node("a").link("b");
Node b = node("b").link("a");
graph().directed().with(a,b)
```
