### ISSUE TITLE
Ambiguous methods in MutableAttributed

### ISSUE THREAD

**Issue by mcanlas** [nidi3/graphviz-java#5]
Aren't these two methods from `MutableAttributed` ambiguous per their types when given two arguments?

```java
    default T add(String name, Object value)

    default T add(Object... keysAndValues)
```

Are both necessary?

**Comment by nidi3** [comment]
When the first parameter is a String, the first method is used, otherwise the second.
The second method alone would be enough, but the first one has a much clearer intent.

It's a question of style. How would you design it?

**Comment by nidi3** [comment]
Scala would provide more design possibilities here, I guess.

**Comment by nidi3** [comment]
now it is
```java
default T add(String name, Object value) 
default T add(Attributes... attributes) 
```
