### ISSUE TITLE
Headlabel and Taillabel for edges are missing

### ISSUE THREAD

**Issue by korbinianweidinger** [nidi3/graphviz-java#54]
I'm building a parser/renderer for .json to UML for work. -> .dot example for an edge would be: 
"node1" -- "node3" ["headlabel"="(1,*)",
    "taillabel"="(0,1)"]
Can I or someone else add this feature, because the code is just a lot prettier not using a string builder for .dot but this lib only supports Label if I am not mistaken :) 
PS: nice work so far

**Comment by nidi3** [comment]
You can add any attributes to links/edges this way: `node("node1").link(to(node("node3")).with("headlabel", "(1,*)"))`

**Comment by nidi3** [comment]
And now also `node("node1").link(to(node("node3")).with(Label.of("(1,*)").head()))`
