### ISSUE TITLE
Label justification of the graph won't emitted correctly

### ISSUE THREAD

**Issue by vanniktech** [nidi3/graphviz-java#56]
Failing test case:

```kotlin
val graph = mutGraph("test")
graph.generalAttrs().add(Label.of("my custom header").locate(TOP).justify(MIDDLE))
assertThat(graph).hasToString("""
    graph "test" {
    "labelloc"="t"
    "label"="my custom header"
    }
    """.trimIndent())
```

Somehow the `labeljust=c` got missing. I'm using 0.4.0

**Comment by vanniktech** [comment]
This could also be working as expected since `labeljust=c` is the default. When I'm changing to left/right I do get `labeljust`. If that's the case please close this.

Some javadoc would help nonetheless to clarify this behavior.

**Comment by nidi3** [comment]
It's exactly as you suspected. Further, in [the doc](https://graphviz.gitlab.io/_pages/doc/info/attrs.html#d:labeljust) `c` is not even mentioned.
Javadoc is not very used in this project, I agree...
