### ISSUE TITLE
How to link nodes on the fly?

### ISSUE THREAD

**Issue by AleKrabbe** [nidi3/graphviz-java#62]
Hello, I'm building an application that creates a control flow graph from source code. So as my parser scans teh source code it is supposed to generate nodes and link them together, and at the end create a graph with the nodes previously created. How can I achieve this? I was thinking something along the lines of:

```
graph = new File("graphs/ex1.png");
Node root = node("a");        
root.link(node("b"));
root.link(node("c"));
Graph g = graph("example1").directed().with(root);
Graphviz.fromGraph(g).width(2000).render(Format.PNG).toFile(graph);
```

However this does not work, it only creates a graph with the root node. Thank you.

**Comment by nidi3** [comment]
Nodes are immutable, therefore `root.link(node("b"))` creates a new node linked to b, but the original `root` is not changed.
So `Node root = node("a").link(node("b"), node("c"));` does what you want.

**Comment by nidi3** [comment]
Suppose that solved it.
