### ISSUE TITLE
Android Studio: Failed to process

### ISSUE THREAD

**Issue by simra1311** [nidi3/graphviz-java#64]
I'm getting a lot of errors and warnings on android studio when I run this code:
`if (android.os.Build.VERSION.SDK_INT > 24) {
            Graph g = graph("example1").directed().with(node("a").link(node("b")));
            try {
                Graphviz.fromGraph(g).width(200).render(Format.PNG).toFile(new File("example/ex1.png"));
            } catch (IOException e) {
                e.printStackTrace();
            }
        }`
Some issues are: 
Static interface methods are only supported starting with Android N (--min-api 24): guru.nidi.graphviz.attribute.Attributes guru.nidi.graphviz.attribute.Attributes.attr(java.lang.String, java.lang.Object)
Message{kind=ERROR, text=Static interface methods are only supported starting with Android N (--min-api 24): guru.nidi.graphviz.attribute.Attributes guru.nidi.graphviz.attribute.Attributes.attr(java.lang.String, java.lang.Object), sources=[Unknown source file], tool name=Optional.of(D8)}

Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete

Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /home/simra/.gradle/caches/modules-2/files-2.1/guru.nidi/graphviz-java/0.2.3/9b69af16154221cc327d19be9b40a73cb4d3b7cc/graphviz-java-0.2.3.jar

Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.

**Comment by nidi3** [comment]
I don't know android too good but some language constructs seem only to be supported with API>24.
The `if` is not enough, I think you must run the compiler with `--min-api 24`

**Comment by vanniktech** [comment]
The problem is likely a java 8 feature that's being used here that is only available on min sdk 24.

For instance any of the java 8 api's, default method or any other new goodie.

**Comment by simra1311** [comment]
I'm getting this on changing the min API to 24. Even changing it to 26 doesn't help.
 `Invoke-customs are only supported starting with Android O (--min-api 26)
Message{kind=ERROR, text=Invoke-customs are only supported starting with Android O (--min-api 26), sources=[Unknown source file], tool name=Optional.of(D8)}`

**Comment by simra1311** [comment]
There seems to be some error in it's java file...

**Comment by nidi3** [comment]
Are you sure you're using min-api 26? 
The error message suggests you're not.

**Comment by nidi3** [comment]
Any news on this?

**Comment by RameshPokharel** [comment]
add this in app level build.gradle 
> android{
  compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

**Comment by nidi3** [comment]
thanks @rameshpokharel. I suppose this is the solution.
