### ISSUE TITLE
Labelling nodes externally

### ISSUE THREAD

**Issue by SyCode7** [nidi3/graphviz-java#68]
I am trying to place labels outside the nodes e.g. besides the nodes additional to labels inside the node. See the sample image  ... the arrows point to what I am aiming to achieve.  Can you advise on how to go about this, is it supported by nidi3 ?
![example_attack_graph](https://user-images.githubusercontent.com/6909640/41279776-aa983020-6e2d-11e8-9cb1-50ecf191d59e.png)

**Comment by nidi3** [comment]
Try `node("http(0,1)").with(Label.of("0.75").external())`

**Comment by SyCode7** [comment]
@nidi3 I have tried unfortunately, ther eis no joy yet. It seems the API supports different `Label` implementations. For example using the code below - 
`Graph ggg = graph("example2").directed().with(node("http(0,1)").with(Label.of("0.75").external()),`
`.with(node("main").with(Shape.RECTANGLE).link(to(node("parse").link(execute)).with("weight", 8),`
`init.link(mkString));`
`Graphviz.fromGraph(ggg).width(900).render(Format.PNG).toFile(new File("example/ex2.png")));
`

The `.external()` always has the error `The method external() is undefined for the type Label`.

**Comment by nidi3** [comment]
Are you using the newest 0.5.2 version?

**Comment by SyCode7** [comment]
I don't think this is available publicly, according to your documentation, this is available through maven : 

<dependency>
    <groupId>guru.nidi</groupId>
    <artifactId>graphviz-java</artifactId>
    <version>0.2.3</version>
</dependency>

**Comment by nidi3** [comment]
just put 0.5.2 instead of 0.2.3 in pom.xml ;)
I updated the readme file accordingly.

**Comment by nidi3** [comment]
I guess it's solved.
