### ISSUE TITLE
Graph that is composed by subgraphs is not equal to the same graph that is built by using only nodes

### ISSUE THREAD

**Issue by sparsick** [nidi3/graphviz-java#7]
Hello Stefan,

thank you for your great work. 

I note, when I run following test code, I get an AssertionError:

```java
        Graph graph1 = graph().directed().with((node("a").link(node("b"), node("c"))));;
        Graph graph2 = graph().directed().with((node("c").link(node("d"), node("e"))));;
        Graph composedGraph = graph().directed().with(graph1, graph2);
        Graph similarGraph = graph().directed().with(node("a").link(node("b"), node("c")),node("c").link(node("d"), node("e")));

        assertEquals(similarGraph, composedGraph);
```

My comparision view shows me following difference:

![grafik](https://cloud.githubusercontent.com/assets/976007/24653347/c7dd9a74-1935-11e7-8ad3-d1ac82dc3886.png)

But both graphs are rendered as expected:

![ex2](https://cloud.githubusercontent.com/assets/976007/24653300/8df0febe-1935-11e7-8991-abd0a1acef07.png)

For me the expected result for `assertEquals(similarGraph, composedGraph)` is `true`. Or maybe a `normalize()` method for the Graph onject would be helpful.

**Comment by nidi3** [comment]
Hi there
A subgraph is more than the sum of its nodes and links.
It can be used to specify common attributes:
```
Graph graph1 = graph("a").nodeAttr().with(Color.RED).with((node("a").link(node("b"), node("c"))));;
Graph graph2 = graph("b").with((node("c").link(node("d"), node("e"))));;
Graph composedGraph = graph().directed().with(graph1, graph2);
```
or to build [clusters](http://www.graphviz.org/Gallery/directed/cluster.html):
```
Graph graph1 = graph().cluster().with((node("a").link(node("b"), node("c"))));;
Graph graph2 = graph().with((node("c").link(node("d"), node("e"))));;
Graph composedGraph = graph().directed().with(graph1, graph2);
```

**Comment by sparsick** [comment]
ok, I see. Thank you for clarifying.
