### ISSUE TITLE
Color the text

### ISSUE THREAD

**Issue by vanniktech** [nidi3/graphviz-java#71]
Is there any way to color the text? Coloring a node can be done via `node.add(Style.FILLED, Color.rgb("#212121"))`

I'd like to have a white text on that grey / black-ish background.

**Comment by vanniktech** [comment]
Found a way to do it:

```kotlin
node.add(Style.FILLED, Color.rgb("#212121"))
  .add("fontcolor", "#ffffff")
```

Should we add `FontColor` which is pretty much equal to `Color`?

**Comment by nidi3** [comment]
you can use `Color.rgb("ffffff").font()`

**Comment by vanniktech** [comment]
Would be worth mentioning that in the README as there is currently no sample for that.

**Comment by nidi3** [comment]
Thanks for the tip, I added this to one of the examples in readme.
