### ISSUE TITLE
Overlapping arrows and xlabels

### ISSUE THREAD

**Issue by timstrauss** [nidi3/graphviz-java#73]
Is it somehow possible to prevent the arrows to cross an external label?
![company-team1-data-d719e14a-9559-41fb-bf09-1ef9a35a0b12](https://user-images.githubusercontent.com/21213658/42873403-360ed0a6-8a7f-11e8-9259-fd0ee9f1dd81.png)

**Comment by nidi3** [comment]
This is a dot question and is not specific to this library. Maybe ask stackoverflow.
Or maybe using `EndLabel.head` or `EndLabel.tail` could help.
