### ISSUE TITLE
Rank nodes on the same rank

### ISSUE THREAD

**Issue by vanniktech** [nidi3/graphviz-java#79]
In dot it's possible to rank certain nodes on the same level using `{rank = same; "node-1"; "node-2"}` etc.

As I'm processing which nodes I want to add in the end I want to align certain nodes of them in the same direction. Is there any particular API for that?

**Comment by nidi3** [comment]
just add a subgraph with graphAttribute Rank
```
graph().with(
    graph().graphAttr().with(Rank.SAME).with(node("node-1"), node("node-2"))
    ...
);
```

**Comment by vanniktech** [comment]
Thanks. This works nicely. Might be worth adding a sample to the readme.
