### ISSUE TITLE
Bug in Node hash function

### ISSUE THREAD

**Issue by omidb** [nidi3/graphviz-java#80]
The hash function for the node is just using source node and the edge to create a hash. In situations that we have something like following the `add` function won't add to set of nodes in the graph.

a --k1-->b
a --k1 -->c

one of the above gets deleted in the hash set!
here is the code:
```java
    public int hashCode() {
        int result = this.name != null ? this.name.hashCode() : 0;
        result = 31 * result + (this.links != null ? this.links.hashCode() : 0);
        result = 31 * result + (this.attributes != null ? this.attributes.hashCode() : 0);
        return result;
    }
```

**Comment by nidi3** [comment]
Should finally be fixed in `0.12.1`
