### ISSUE TITLE
MutableGraph#addLink does not work as expected

### ISSUE THREAD

**Issue by vanniktech** [nidi3/graphviz-java#84]
Given the code below:

```kotlin
val a = mutNode("a")
val b = mutNode("b")
return mutGraph()
    .add(a)
    .add(b)
    .addLink(Link.between(a, b))
```

I'd expect to have a graph connecting a and b. However, the graph below will be generated:

![project-dependency-graph](https://user-images.githubusercontent.com/5759366/45366515-4c76f900-b5df-11e8-844c-64e78489d2ad.png)

**Comment by nidi3** [comment]
Me too...

**Comment by vanniktech** [comment]
Using the latest version (0.6.0).

**Comment by nidi3** [comment]
This was already broken before 0.6.0

**Comment by vanniktech** [comment]
> The naming could signify both uses.

Yeah it does. Is there any other function which does what I want?

> This was already broken before 0.6.0

Yup. I've been on 0.5.x before just wanted to point out that it's also broken on latest release.

**Comment by nidi3** [comment]
I think the creation of a `Link(from,to)` should be impossible.
Only `Link(to)` and `Link(port,to)`

**Comment by nidi3** [comment]
You can do simply `mutGraph().add(a.addLink(b))`

**Comment by vanniktech** [comment]
`mutGraph().add(a.addLink(b))` that does the trick. However, how can I make the line that is being drawn dotted?

**Comment by nidi3** [comment]
Ah, and btw with new kotlin DSL, you can even write `graph() {"a" - "b"}`

**Comment by vanniktech** [comment]
`a.addLink(b).add(Style.DOTTED)` makes the Node dotted and not the line.

**Comment by nidi3** [comment]
`a.addLink(to(b).with(Style.DOTTED))` or `("a" - "b")[Style.DOTTED]`

**Comment by vanniktech** [comment]
That's perfect. I've got everything I need now. Feel free to close this issue if you want.

**Comment by nidi3** [comment]
Good to hear. 
I keep the issue open as a reminder for an API improvement regarding Links.

**Comment by nidi3** [comment]
In 0.7.0 there is only `Link.between(port, LinkTarget)` to avoid this kind of missunderstanding.
