### ISSUE TITLE
Font width is not always calculated correctly

### ISSUE THREAD

**Issue by nidi3** [nidi3/graphviz-java#85]
I have just noticed another issue: sometimes, when long labels are used, they are drawn outside the node borders. This usually happens when: (i) using shapes different than the default circles, (ii) using HTML labels even in circle shapes. With the following piece of code, I obtain the image in attach:

Node node1 = node("1-very-long-text-that-may-overlap-borders").with(Shape.RECTANGLE);
Node node2 = node(Label.html("2-very-long-text-that-may-overlap-borders"));
Node node3 = node("another-very-long-text-that-may-overlap-borders");
Graph g =
    graph("example1").directed()
        .with(node1.link(node2))
        .with(node2.link(node3));
g = g.nodeAttr().with(Font.config("Arial", 10));

Graphviz.fromGraph(g).width(400).render(Format.PNG).toFile(new File("images/example1.png"));
Graphviz.fromGraph(g).width(400).render(Format.XDOT).toFile(new File("images/example1.xdot"));

However, the corresponding DOT is rendered nicely using a Graphviz viewer (such as https://dreampuf.github.io/GraphvizOnline/). Can you have a look at this issue?

**Comment by nidi3** [comment]
Added the fontAdjust option to solve the problem at least manually.

**Comment by nidi3** [comment]
See https://github.com/nidi3/graphviz-java#font-size

**Comment by nidi3** [comment]
Still not perfect. Seems to be only a problem with Js engines, native engine is ok.

**Comment by plc-dev** [comment]
@nidi3 
Hello Stefan, have you ever had a chance to revisit this?
It seems as the issue persists to this day.
I am indirectly using this package as part of Schemacrawler (www.schemacrawler.com), as to why I'm unable to apply the manual solution.

The resulting graph results in these cut off titles:
![academic](https://user-images.githubusercontent.com/33401663/75096323-e4339180-559e-11ea-9f1c-c7cd4bcd5385.png)

**Comment by nidi3** [comment]
You are right, the problem still exists and I fear that there is no clean solution to it.
However, I might have an idea how to improve the current state of it.
But I don't know if this will help with your concrete problem, maybe open an issue also on their project.

**Comment by nidi3** [comment]
After a deep dive into Emscripten and C language, the font width calculation should be way better in version `0.15.0`.
I hope this will also improve the issue with schemacrawler as soon as they update.
