### ISSUE TITLE
How to creat cluster in MutableGraph

### ISSUE THREAD

**Issue by wx930910** [nidi3/graphviz-java#87]
I know how to creat different cluster for a normal graph, is there anyway for me to create cluster for a mutableGraph? just like belowed figure:
![image](https://user-images.githubusercontent.com/22060531/47607441-fd015680-d9ed-11e8-9dd6-176b439cd96d.png)

1. I tried to create 2 mutableGraph and use addTo function to aggregate them into one mutableGraph, but the border of the graph seems not work as expected (Red node and yellow node are from 2 mutableGraph). 

2. I don't know how to create the links between nodes in different graph:
![test](https://user-images.githubusercontent.com/22060531/47607478-86b12400-d9ee-11e8-9c62-32b3d223c9c3.png)

Any hint would be would be greatly appreciated!

**Comment by nidi3** [comment]
`MutableGraph.setCluster(true)`?

**Comment by nidi3** [comment]
Complete example: 

    MutableGraph g = mutGraph().add(
                node("start").link("a0", "b0"),
                mutGraph("a").setCluster(true).add(node("a0").link("a1")),
                mutGraph("b").setCluster(true).add(node("b0").link("b1").link("a1"))
        );

**Comment by jinfenglin** [comment]
When I try to connect node in a cluster to a node outside a cluster, the out side node will be automatically merged into the graph, I believe it might be a bug. 
This is how I create the link:
`                MutableGraph fromSubGraph = (MutableGraph) from;
                fromSubGraph = fromSubGraph.setCluster(true);
                Vertex fromSubGraphSinkNode = ((SGraph) sourceVertex).sinkNode;
                LinkSource sinkNode = fromSubGraph.nodes().stream().filter(x -> x.name().value().equals(fromSubGraphSinkNode.getVertexId())).findFirst().get();
                for (Vertex targetVertex : sourceVertex.getOutputVertices()) {
                    LinkTarget toTarget = nodeMap.get(targetVertex).asLinkTarget();
                    sinkNode.links().add(sinkNode.linkTo(toTarget).with(Label.of(linkLabel)));
                }`
![image](https://user-images.githubusercontent.com/6909298/52175812-6f18d280-2777-11e9-840a-5e918264961b.png)

**Comment by nidi3** [comment]
I cannot exactly reproduce the problem, but I think you want the second SinkNode outside of the cluster. For this, all links to it must also be defined outside of the cluster, otherwise the node is merged into the cluster. This is how graphviz works.

Here sink2 is inside the cluster:
```
graph().with(
                node("sourceNode").link("tokenizer").link("source"),
                node("tokenizer").link("sink2"),
                graph("sub").cluster().with(
                        node("source").link("sink1"),
                        node("sink1").link("sink2"))
        );
```

Here sink2 is outside the cluster:
```
graph().with(
                node("sourceNode").link("tokenizer").link("source"),
                node("tokenizer").link("sink2"),
                node("sink1").link("sink2")
                graph("sub").cluster().with(
                        node("source").link("sink1"))
        );
```

**Comment by jinfenglin** [comment]
Thanks, I put the second sink node outside of the cluster. but the link is inside the subgraph that's why the outside sink node got merged into the cluster.

**Comment by edwinjo555** [comment]
Is there any way to create and display the label of the cluster?

For example, "process #1" and "process #2" in the following figure :


![download](https://user-images.githubusercontent.com/40605196/64414935-ec137e00-d0b1-11e9-9172-d4b633ff225c.png)

**Comment by nidi3** [comment]
Simply add a label: `graph().cluster().graphAttr().with(Label.of("process #1"))`

**Comment by LeeReindeer** [comment]
Hi there, I want to link two subgraphs like the dot file show below.
```dot
digraph {
subgraph "cluster_a" {
"a0" -> "a1"
}
subgraph "cluster_b" {
"b0" -> "b1"
}
"a1" -> "b0"
}
```
The  graphviz commond line works fine with this, but when try to create graph like this in Java API, it's not work as expected.
Here's my code
```Java
    MutableNode a0 = mutNode("a0");
    MutableNode a1 = mutNode("a1");
    MutableNode b0 = mutNode("b0");
    MutableNode b1 = mutNode("b1");
    a0.addLink(a1);
    a1.addLink(b0);
    b0.addLink(b1);
    MutableGraph g = mutGraph().setDirected(true).add(
        mutGraph("a").setCluster(true).setDirected(true).add(a0),
        mutGraph("b").setCluster(true).setDirected(true).add(b0)
    );
```
out:
```dot
digraph {
subgraph "cluster_a" {
"a0" -> "a1"
"a1" -> "b0"
"b0" -> "b1"
}
subgraph "cluster_b" {
"b0" -> "b1"
}
}
```
And also tried:
```java
    a0.addLink(a1);
    b0.addLink(b1);

    MutableGraph g = mutGraph().setDirected(true).add(
        mutGraph("a").setCluster(true).setDirected(true).add(a0),
        mutGraph("b").setCluster(true).setDirected(true).add(b0),
        a1.linkTo(b0).asLinkSource()
    );
```
output:
```dot
digraph {
subgraph "cluster_a" {
"a0" -> "a1"
}
subgraph "cluster_b" {
"b0" -> "b1"
}
"b0" -> "b1"
}
```
Any solution? thanks

**Comment by LeeReindeer** [comment]
ok, I've figured out by reading these [source code](https://github.com/nidi3/graphviz-java/blob/15d366cf85c5bbd089bed8844cbd6234f5f52200/graphviz-java/src/main/java/guru/nidi/graphviz/parse/ParserImpl.java#L176), but not that graceful.

```java
    MutableNode a0 = mutNode("a0");
    MutableNode a1 = mutNode("a1");
    MutableNode b0 = mutNode("b0");
    MutableNode b1 = mutNode("b1");
    a0.addLink(a1);
    b0.addLink(b1);

    MutableGraph g = mutGraph().setDirected(true).add(
        mutGraph("a").setCluster(true).setDirected(true).add(a0),
        mutGraph("b").setCluster(true).setDirected(true).add(b0)
    );
    LinkSource from = mutNode("a1");
    LinkSource to = mutNode("b0");
    from.links().add(from.linkTo((LinkTarget) to));
    g.add(from);
```
