### ISSUE TITLE
Convert Graph to MutableGrap and inverse

### ISSUE THREAD

**Issue by gotson** [nidi3/graphviz-java#90]
I would like to know how i could:

1. convert or cast a MutableGraph to a Graph
2. convert a Graph to a MutableGraph

I see that MutableGraph does not implement Graph, which prevents casting. But maybe there is an explicit function to convert from one to the other ?

**Comment by nidi3** [comment]
You can cast a `Graph` into a `MutableGraph`.
There is a method for the inverse, but it's currently private.

Why do you need to do this?

**Comment by gotson** [comment]
The `Parser` returns a `MutableGraph`, and i want to design my business logic around `Graph` since it's not modifying the graphs, but i can't because of that.

So all my code is now taking a `MutableGraph`, it's not very clean.

**Comment by nidi3** [comment]
Finally after more than a year...
