### ISSUE TITLE
Text Alignment in Node

### ISSUE THREAD

**Issue by luxmar** [nidi3/graphviz-java#95]
Is there a way for text alignment inside a node? By default, the text inside a node is centered.
I have a Label.html(.....) method and need a left alignment for the text. 
Can someone provide an working example? Is there a way to use all common HTML elements inside a Label.html method? Or even to inject CSS? The latter would enable many styling options.

**Comment by nidi3** [comment]
See https://graphviz.gitlab.io/_pages/doc/info/attrs.html#k:escString
\l and \r can be used to justify label lines:
```
Graph g = graph().with(
  node("a").with(Label.of("center\nleft\\lright\\r"))
  .link(node("b")));
```

**Comment by nidi3** [comment]
For HTML labels, see https://graphviz.gitlab.io/_pages/doc/info/shapes.html#html
So it would be: 
`g = g.with(node( Label.html("<b>Summary</b>" + "<br align=\"left\"/>Serach Terms: " + logActivitiesHMapClean.size() + "<br align=\"left\"/>Frequency Search Entries: " + logEntriesClean.size() )).with(Shape.RECTANGLE,Style.FILLED, Color.rgb(fixNodeColor.getRGB())));`

**Comment by nidi3** [comment]
I just added a new method for this use case:
`g = g.with(node( Label.htmlLines(LEFT, "<b>Summary</b>", "Serach Terms: " + logActivitiesHMapClean.size(), "Frequency Search Entries: " + logEntriesClean.size() )).with(Shape.RECTANGLE,Style.FILLED, Color.rgb(fixNodeColor.getRGB())));`

Version 0.8.1 should be available later today.

**Comment by luxmar** [comment]
Thank you so much. This helped a lot and works now. I will also try your new method!
