### ISSUE TITLE
Graph dimension

### ISSUE THREAD

**Issue by luigi-asprino** [nidi3/graphviz-java#97]
Hi,

is there any way to force the engine to place nodes within a given width without reducing the resolution or shrinking the text?
I know that exists .width(int) but it seems that it only reduces the resolution of the image.

Thanks 

Luigi

**Comment by nidi3** [comment]
I don't have the impression that `width` reduces the resolution.
Can you attach an example?

**Comment by luigi-asprino** [comment]
Hi 

Here is a simple example. 
In the second image instead of placing the nodes vertically (in the 2000px), the render still places nodes horizontally.
The result is that the image is a shrunk version of the first.

`public static void main(String[] args) throws IOException {
		MutableNode a = mutNode("a");
		MutableNode b = mutNode("b");
		MutableNode c = mutNode("c");
		MutableNode d = mutNode("d");
		MutableNode e = mutNode("e");
		MutableNode f = mutNode("f");
		MutableNode g = mutNode("g");
		MutableNode h = mutNode("h");
		MutableNode i = mutNode("i");
		MutableNode l = mutNode("l");
		MutableNode m = mutNode("m");
		MutableNode n = mutNode("n");
		MutableNode o = mutNode("o");
		a.addLink(b, c, d, e, f, g, h, i, l, m, n, o);
		MutableNode[] nodes = { a, b, c, d, e, f, g, h, i, l, m, n, o };
		Graph graph = graph("test").directed().graphAttr().with(RankDir.TOP_TO_BOTTOM, guru.nidi.graphviz.attribute.Font.size(40)).with(nodes);
		Graphviz.fromGraph(graph).width(1000).height(2000).render(Format.PNG).toFile(new File("example/ex1_1000.png"));
		Graphviz.fromGraph(graph).width(100).height(2000).render(Format.PNG).toFile(new File("example/ex1_100.png"));
	}`




![ex1_1000](https://user-images.githubusercontent.com/11695205/52220392-0593e380-289f-11e9-8b5b-93cd6da9e0d3.png)


![ex1_100](https://user-images.githubusercontent.com/11695205/52220386-0298f300-289f-11e9-908b-7ddd2083b161.png)

**Comment by nidi3** [comment]
The size you give is applied after the layouting is done.
When you want vertical alignment, you can use `RankDir.LEFT_TO_RIGHT`

**Comment by luigi-asprino** [comment]
Hi,

thanks for the answer. 
Is there any way to impose size before the layouting?
Maybe this is a better example that I've created by giving `RankDir.LEFT_TO_RIGHT`.
A better solution for the first image would be placing b1-b5 vertically under o.

![ex1_100](https://user-images.githubusercontent.com/11695205/52270661-e8fcb780-2941-11e9-98f8-fe5ad64a9d05.png)
![ex1_1000](https://user-images.githubusercontent.com/11695205/52270666-ed28d500-2941-11e9-8b5b-6f0e7c00dd38.png)

**Comment by nidi3** [comment]
Probably you can achieve something by using various subgraphs with different `RankDir` settings. 
But as I understand it, graphviz is not designed to automatically fill a given width/height.
Maybe a graphviz forum can help you better.
