### ISSUE TITLE
Change edge width

### ISSUE THREAD

**Issue by luxmar** [nidi3/graphviz-java#99]
Is there a way to change the edge width e.g, on pixel level?

In your tutorials from your project page there is only the attribute `Style.BOLD` which defines the edge width in just 2 ways (setting bold and without setting anything). I have not figured out a way to define more granularities for the printed edge thickness.

**Comment by nidi3** [comment]
use`Style.lineWidth()`:
```
graph()
  .linkAttr().with(Style.lineWidth(5))
  .with(node("a").link("b"))
```

**Comment by luxmar** [comment]
Thank you very much! That worked for me!
